// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Honua.Admin.Models.Admin;

/// <summary>
/// Source-generated JSON serializer context for admin DTOs. Mirrors the
/// <c>SpecWorkspaceJsonContext</c> pattern so the admin paths are AOT/trim
/// friendly when the WebAssembly project ships.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ConnectionSummary))]
[JsonSerializable(typeof(ConnectionSummary[]))]
[JsonSerializable(typeof(ConnectionDetail))]
[JsonSerializable(typeof(CreateConnectionRequest))]
[JsonSerializable(typeof(UpdateConnectionRequest))]
[JsonSerializable(typeof(TestConnectionResult))]
[JsonSerializable(typeof(EncryptionValidationResult))]
[JsonSerializable(typeof(KeyRotationResult))]
[JsonSerializable(typeof(TableDiscoveryResponse))]
[JsonSerializable(typeof(FeatureOverview))]
[JsonSerializable(typeof(ConfigurationSummary))]
[JsonSerializable(typeof(ConfigurationDiscoveryResult))]
[JsonSerializable(typeof(ConfigurationMetadata[]))]
[JsonSerializable(typeof(AutoGeneratedDocumentationSection[]))]
[JsonSerializable(typeof(SecretValidationResult))]
[JsonSerializable(typeof(ConfigurationAuditInfo))]
[JsonSerializable(typeof(LayerSummary))]
[JsonSerializable(typeof(LayerSummary[]))]
[JsonSerializable(typeof(PublishLayerRequest))]
[JsonSerializable(typeof(LayerEnabledRequest))]
[JsonSerializable(typeof(LayerStyle))]
[JsonSerializable(typeof(LayerStyleUpdateRequest))]
[JsonSerializable(typeof(ServiceSummary))]
[JsonSerializable(typeof(ServiceSummary[]))]
[JsonSerializable(typeof(ServiceSettings))]
[JsonSerializable(typeof(UpdateProtocolsRequest))]
[JsonSerializable(typeof(AccessPolicySettings))]
[JsonSerializable(typeof(TimeInfoSettings))]
[JsonSerializable(typeof(MapServerSettings))]
[JsonSerializable(typeof(UpdateLayerMetadataRequest))]
[JsonSerializable(typeof(LayerMetadataResponse))]
[JsonSerializable(typeof(DeployPreflightResult))]
[JsonSerializable(typeof(DeployPlanRequest))]
[JsonSerializable(typeof(CreateDeployOperationRequest))]
[JsonSerializable(typeof(SubmitDeployOperationRequest))]
[JsonSerializable(typeof(RollbackDeployOperationRequest))]
[JsonSerializable(typeof(DeployPlan))]
[JsonSerializable(typeof(DeployOperation))]
[JsonSerializable(typeof(RecentErrorsResponse))]
[JsonSerializable(typeof(ObservabilityStatusResponse))]
[JsonSerializable(typeof(MigrationObservabilityResponse))]
[JsonSerializable(typeof(AdminApiResponse<ConnectionSummary[]>))]
[JsonSerializable(typeof(AdminApiResponse<ConnectionSummary>))]
[JsonSerializable(typeof(AdminApiResponse<ConnectionDetail>))]
[JsonSerializable(typeof(AdminApiResponse<TestConnectionResult>))]
[JsonSerializable(typeof(AdminApiResponse<EncryptionValidationResult>))]
[JsonSerializable(typeof(AdminApiResponse<KeyRotationResult>))]
[JsonSerializable(typeof(AdminApiResponse<FeatureOverview>))]
[JsonSerializable(typeof(AdminApiResponse<LayerSummary[]>))]
[JsonSerializable(typeof(AdminApiResponse<LayerSummary>))]
[JsonSerializable(typeof(AdminApiResponse<LayerStyle>))]
[JsonSerializable(typeof(AdminApiResponse<ServiceSummary[]>))]
[JsonSerializable(typeof(AdminApiResponse<ServiceSettings>))]
[JsonSerializable(typeof(AdminApiResponse<LayerMetadataResponse>))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, int>))]
public sealed partial class AdminJsonContext : JsonSerializerContext
{
}
