// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json.Serialization;

namespace Honua.Admin.Models.Admin;

/// <summary>
/// Current edition and gated feature overview from
/// <c>Admin/FeatureOverviewEndpoints</c>.
/// </summary>
public sealed record FeatureOverview
{
    [JsonPropertyName("currentEdition")] public string CurrentEdition { get; init; } = string.Empty;
    [JsonPropertyName("features")] public IReadOnlyList<FeatureOverviewItem> Features { get; init; } = Array.Empty<FeatureOverviewItem>();

    [JsonIgnore] public int EnabledCount => Features.Count(static feature => feature.IsEnabled);
    [JsonIgnore] public int DisabledCount => Features.Count(static feature => !feature.IsEnabled);
}

public sealed record FeatureOverviewItem
{
    [JsonPropertyName("key")] public string Key { get; init; } = string.Empty;
    [JsonPropertyName("displayName")] public string DisplayName { get; init; } = string.Empty;
    [JsonPropertyName("category")] public string Category { get; init; } = string.Empty;
    [JsonPropertyName("description")] public string Description { get; init; } = string.Empty;
    [JsonPropertyName("isEnabled")] public bool IsEnabled { get; init; }
    [JsonPropertyName("minimumEdition")] public string MinimumEdition { get; init; } = string.Empty;
    [JsonPropertyName("upgradeMessage")] public string? UpgradeMessage { get; init; }
}

/// <summary>
/// High-level configuration summary from
/// <c>GET /admin/configuration/summary</c>.
/// </summary>
public sealed record ConfigurationSummary
{
    [JsonPropertyName("totalTypes")] public int TotalTypes { get; init; }
    [JsonPropertyName("registeredTypes")] public int RegisteredTypes { get; init; }
    [JsonPropertyName("totalProperties")] public int TotalProperties { get; init; }
    [JsonPropertyName("secretProperties")] public int SecretProperties { get; init; }
    [JsonPropertyName("requiredProperties")] public int RequiredProperties { get; init; }
    [JsonPropertyName("typesWithValidation")] public int TypesWithValidation { get; init; }
    [JsonPropertyName("totalSecrets")] public int TotalSecrets { get; init; }
    [JsonPropertyName("validSecrets")] public int ValidSecrets { get; init; }
    [JsonPropertyName("invalidSecrets")] public int InvalidSecrets { get; init; }
    [JsonPropertyName("environment")] public string Environment { get; init; } = string.Empty;
    [JsonPropertyName("discoveryDurationMs")] public long DiscoveryDurationMs { get; init; }
    [JsonPropertyName("lastDiscovery")] public DateTimeOffset LastDiscovery { get; init; }
}

public sealed record ConfigurationDiscoveryResult
{
    [JsonPropertyName("discoveredTypes")] public IReadOnlyList<ConfigurationTypeInfo> DiscoveredTypes { get; init; } = Array.Empty<ConfigurationTypeInfo>();
    [JsonPropertyName("extractedMetadata")] public IReadOnlyList<ConfigurationMetadata> ExtractedMetadata { get; init; } = Array.Empty<ConfigurationMetadata>();
    [JsonPropertyName("autoGeneratedDocumentation")] public IReadOnlyList<AutoGeneratedDocumentationSection> AutoGeneratedDocumentation { get; init; } = Array.Empty<AutoGeneratedDocumentationSection>();
    [JsonPropertyName("secretValidation")] public SecretValidationResult SecretValidation { get; init; } = new();
    [JsonPropertyName("auditInformation")] public ConfigurationAuditInfo AuditInformation { get; init; } = new();
    [JsonPropertyName("discoveryDurationMs")] public long DiscoveryDurationMs { get; init; }
    [JsonPropertyName("timestamp")] public DateTimeOffset Timestamp { get; init; }
}

public sealed record ConfigurationTypeInfo
{
    [JsonPropertyName("sectionName")] public string SectionName { get; init; } = string.Empty;
    [JsonPropertyName("typeName")] public string TypeName { get; init; } = string.Empty;
    [JsonPropertyName("fullTypeName")] public string FullTypeName { get; init; } = string.Empty;
    [JsonPropertyName("assembly")] public string Assembly { get; init; } = string.Empty;
    [JsonPropertyName("properties")] public IReadOnlyList<PropertyMetadata> Properties { get; init; } = Array.Empty<PropertyMetadata>();
    [JsonPropertyName("isRegisteredInDi")] public bool IsRegisteredInDi { get; init; }
}

public sealed record PropertyMetadata
{
    [JsonPropertyName("name")] public string Name { get; init; } = string.Empty;
    [JsonPropertyName("type")] public string Type { get; init; } = string.Empty;
    [JsonPropertyName("isRequired")] public bool IsRequired { get; init; }
    [JsonPropertyName("isSecret")] public bool IsSecret { get; init; }
}

public sealed record ConfigurationMetadata
{
    [JsonPropertyName("sectionName")] public string SectionName { get; init; } = string.Empty;
    [JsonPropertyName("typeName")] public string TypeName { get; init; } = string.Empty;
    [JsonPropertyName("propertyCount")] public int PropertyCount { get; init; }
    [JsonPropertyName("secretPropertyCount")] public int SecretPropertyCount { get; init; }
    [JsonPropertyName("requiredPropertyCount")] public int RequiredPropertyCount { get; init; }
    [JsonPropertyName("hasValidation")] public bool HasValidation { get; init; }
    [JsonPropertyName("isRegistered")] public bool IsRegistered { get; init; }
}

public sealed record AutoGeneratedDocumentationSection
{
    [JsonPropertyName("sectionName")] public string SectionName { get; init; } = string.Empty;
    [JsonPropertyName("typeName")] public string TypeName { get; init; } = string.Empty;
    [JsonPropertyName("description")] public string Description { get; init; } = string.Empty;
    [JsonPropertyName("properties")] public IReadOnlyList<AutoGeneratedPropertyDoc> Properties { get; init; } = Array.Empty<AutoGeneratedPropertyDoc>();
}

public sealed record AutoGeneratedPropertyDoc
{
    [JsonPropertyName("name")] public string Name { get; init; } = string.Empty;
    [JsonPropertyName("type")] public string Type { get; init; } = string.Empty;
    [JsonPropertyName("description")] public string Description { get; init; } = string.Empty;
    [JsonPropertyName("isRequired")] public bool IsRequired { get; init; }
    [JsonPropertyName("isSecret")] public bool IsSecret { get; init; }
    [JsonPropertyName("environmentVariable")] public string EnvironmentVariable { get; init; } = string.Empty;
}

public sealed record SecretValidationResult
{
    [JsonPropertyName("totalSecrets")] public int TotalSecrets { get; init; }
    [JsonPropertyName("validSecrets")] public int ValidSecrets { get; init; }
    [JsonPropertyName("invalidSecrets")] public int InvalidSecrets { get; init; }
    [JsonPropertyName("issues")] public IReadOnlyList<SecretValidationIssue> Issues { get; init; } = Array.Empty<SecretValidationIssue>();
}

public sealed record SecretValidationIssue
{
    [JsonPropertyName("secretReference")] public string SecretReference { get; init; } = string.Empty;
    [JsonPropertyName("issue")] public string Issue { get; init; } = string.Empty;
    [JsonPropertyName("severity")] public string Severity { get; init; } = string.Empty;
}

public sealed record ConfigurationAuditInfo
{
    [JsonPropertyName("environment")] public string Environment { get; init; } = string.Empty;
    [JsonPropertyName("machineName")] public string MachineName { get; init; } = string.Empty;
    [JsonPropertyName("applicationName")] public string ApplicationName { get; init; } = string.Empty;
    [JsonPropertyName("contentRoot")] public string ContentRoot { get; init; } = string.Empty;
    [JsonPropertyName("configurationSources")] public IReadOnlyDictionary<string, int> ConfigurationSources { get; init; } = new Dictionary<string, int>();
    [JsonPropertyName("totalConfigurationKeys")] public int TotalConfigurationKeys { get; init; }
}
