// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using System.Threading;
using System.Threading.Tasks;
using Honua.Admin.Models.Admin;
using Honua.Sdk.Admin.Exceptions;
using SdkAdminClient = Honua.Sdk.Admin.IHonuaAdminClient;
using SdkAdminHttpClient = Honua.Sdk.Admin.HonuaAdminClient;

namespace Honua.Admin.Services.Admin;

/// <summary>
/// Admin UI client that delegates SDK-stable REST contracts to Honua.Sdk.Admin
/// while keeping admin-only endpoints in this repo.
/// Authentication and base-URL rebasing live in <c>AdminAuthHandler</c>; 401/CORS
/// handling lives in <c>GlobalErrorHandler</c>.
/// </summary>
public sealed class HonuaAdminClient : IHonuaAdminClient
{
    private const string ApiVersionPrefix = "api/v1/admin";

    private readonly HttpClient _http;
    private readonly IAdminTelemetry _telemetry;
    private readonly SdkAdminClient _sdk;

    public HonuaAdminClient(HttpClient http, IAdminTelemetry telemetry)
        : this(http, telemetry, new SdkAdminHttpClient(http))
    {
    }

    public HonuaAdminClient(HttpClient http, IAdminTelemetry telemetry, SdkAdminClient sdk)
    {
        _http = http;
        _telemetry = telemetry;
        _sdk = sdk;
    }

    public Task<FeatureOverview> GetFeatureOverviewAsync(CancellationToken cancellationToken)
        => GetApiAsync(nameof(GetFeatureOverviewAsync), $"{ApiVersionPrefix}/features/", TypeInfo<AdminApiResponse<FeatureOverview>>(), cancellationToken);

    public Task<ConfigurationSummary> GetConfigurationSummaryAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetConfigurationSummaryAsync), $"{ApiVersionPrefix}/configuration/summary", TypeInfo<ConfigurationSummary>(), cancellationToken);

    public Task<ConfigurationDiscoveryResult> DiscoverConfigurationAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(DiscoverConfigurationAsync), $"{ApiVersionPrefix}/configuration/discover", TypeInfo<ConfigurationDiscoveryResult>(), cancellationToken);

    public async Task<IReadOnlyList<ConfigurationMetadata>> GetConfigurationMetadataAsync(CancellationToken cancellationToken)
        => await GetAsync(nameof(GetConfigurationMetadataAsync), $"{ApiVersionPrefix}/configuration/metadata", TypeInfo<ConfigurationMetadata[]>(), cancellationToken)
            .ConfigureAwait(false);

    public async Task<IReadOnlyList<AutoGeneratedDocumentationSection>> GetConfigurationAutoDocumentationAsync(CancellationToken cancellationToken)
        => await GetAsync(nameof(GetConfigurationAutoDocumentationAsync), $"{ApiVersionPrefix}/configuration/auto-documentation", TypeInfo<AutoGeneratedDocumentationSection[]>(), cancellationToken)
            .ConfigureAwait(false);

    public Task<SecretValidationResult> ValidateConfigurationSecretsAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(ValidateConfigurationSecretsAsync), $"{ApiVersionPrefix}/configuration/secrets/validate", TypeInfo<SecretValidationResult>(), cancellationToken);

    public Task<ConfigurationAuditInfo> GetConfigurationAuditInfoAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetConfigurationAuditInfoAsync), $"{ApiVersionPrefix}/configuration/audit", TypeInfo<ConfigurationAuditInfo>(), cancellationToken);

    public Task<JsonElement> GetConfigurationDocumentAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetConfigurationDocumentAsync), $"{ApiVersionPrefix}/config", TypeInfo<JsonElement>(), cancellationToken);

    public Task<JsonElement> GetAdminOpenApiAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetAdminOpenApiAsync), $"{ApiVersionPrefix}/openapi.json", TypeInfo<JsonElement>(), cancellationToken);

    public async Task<IReadOnlyList<ConnectionSummary>> ListConnectionsAsync(CancellationToken cancellationToken)
        => await ExecuteSdkAsync(
                nameof(ListConnectionsAsync),
                async ct => SdkAdminModelMapper.MapList(
                    await _sdk.ListConnectionsAsync(ct).ConfigureAwait(false),
                    SdkAdminModelMapper.ToConnectionSummary),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<ConnectionDetail> GetConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetConnectionAsync),
            async ct => SdkAdminModelMapper.ToConnectionDetail(await _sdk.GetConnectionAsync(connectionId, ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<ConnectionSummary> CreateConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(CreateConnectionAsync),
            async ct => SdkAdminModelMapper.ToConnectionSummary(
                await _sdk.CreateConnectionAsync(SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<ConnectionSummary> UpdateConnectionAsync(string connectionId, UpdateConnectionRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(UpdateConnectionAsync),
            async ct => SdkAdminModelMapper.ToConnectionSummary(
                await _sdk.UpdateConnectionAsync(connectionId, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task DeleteConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(DeleteConnectionAsync),
            async ct =>
        {
            await _sdk.DeleteConnectionAsync(connectionId, ct).ConfigureAwait(false);
        },
            cancellationToken);

    public Task<TestConnectionResult> TestDraftConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(TestDraftConnectionAsync),
            async ct => SdkAdminModelMapper.ToTestConnectionResult(
                await _sdk.TestDraftConnectionAsync(SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<TestConnectionResult> TestConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(TestConnectionAsync),
            async ct => SdkAdminModelMapper.ToTestConnectionResult(await _sdk.TestConnectionAsync(connectionId, ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<EncryptionValidationResult> ValidateEncryptionAsync(CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(ValidateEncryptionAsync),
            async ct => SdkAdminModelMapper.ToEncryptionValidationResult(await _sdk.ValidateEncryptionAsync(ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<KeyRotationResult> RotateEncryptionKeyAsync(CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(RotateEncryptionKeyAsync),
            async ct => SdkAdminModelMapper.ToKeyRotationResult(await _sdk.RotateEncryptionKeyAsync(ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<IReadOnlyList<DiscoveredTable>> DiscoverConnectionTablesAsync(string connectionId, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(DiscoverConnectionTablesAsync),
            async ct => SdkAdminModelMapper.MapList(
                (await _sdk.DiscoverTablesAsync(connectionId, ct).ConfigureAwait(false)).Tables,
                SdkAdminModelMapper.ToDiscoveredTable),
            cancellationToken);

    public async Task<IReadOnlyList<LayerSummary>> ListLayersAsync(string connectionId, string? serviceName, CancellationToken cancellationToken)
        => await ExecuteSdkAsync(
                nameof(ListLayersAsync),
                async ct => SdkAdminModelMapper.MapList(
                    await _sdk.ListLayersAsync(connectionId, serviceName, ct).ConfigureAwait(false),
                    SdkAdminModelMapper.ToLayerSummary),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<LayerSummary> PublishLayerAsync(string connectionId, PublishLayerRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(PublishLayerAsync),
            async ct => SdkAdminModelMapper.ToLayerSummary(
                await _sdk.PublishLayerAsync(connectionId, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<LayerSummary> SetLayerEnabledAsync(string connectionId, int layerId, bool enabled, string? serviceName, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(SetLayerEnabledAsync),
            async ct => SdkAdminModelMapper.ToLayerSummary(
                await _sdk.SetLayerEnabledAsync(connectionId, layerId, enabled, serviceName, ct).ConfigureAwait(false)),
            cancellationToken);

    public async Task<IReadOnlyList<LayerSummary>> SetServiceLayersEnabledAsync(string connectionId, bool enabled, string? serviceName, CancellationToken cancellationToken)
        => await ExecuteSdkAsync(
                nameof(SetServiceLayersEnabledAsync),
                async ct => SdkAdminModelMapper.MapList(
                    await _sdk.SetServiceLayersEnabledAsync(connectionId, enabled, serviceName, ct).ConfigureAwait(false),
                    SdkAdminModelMapper.ToLayerSummary),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<LayerStyle> GetLayerStyleAsync(int layerId, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetLayerStyleAsync),
            async ct => SdkAdminModelMapper.ToLayerStyle(await _sdk.GetLayerStyleAsync(layerId, ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<LayerStyle> UpdateLayerStyleAsync(int layerId, LayerStyleUpdateRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(UpdateLayerStyleAsync),
            async ct => SdkAdminModelMapper.ToLayerStyle(
                await _sdk.UpdateLayerStyleAsync(layerId, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public async Task<IReadOnlyList<ServiceSummary>> ListServicesAsync(CancellationToken cancellationToken)
        => await ExecuteSdkAsync(
                nameof(ListServicesAsync),
                async ct => SdkAdminModelMapper.MapList(
                    await _sdk.ListServicesAsync(ct).ConfigureAwait(false),
                    SdkAdminModelMapper.ToServiceSummary),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<ServiceSettings> GetServiceSettingsAsync(string serviceName, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetServiceSettingsAsync),
            async ct => SdkAdminModelMapper.ToServiceSettings(await _sdk.GetServiceSettingsAsync(serviceName, ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<ServiceSettings> UpdateServiceProtocolsAsync(string serviceName, UpdateProtocolsRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(UpdateServiceProtocolsAsync),
            async ct => SdkAdminModelMapper.ToServiceSettings(
                await _sdk.UpdateProtocolsAsync(serviceName, request.EnabledProtocols, ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<ServiceSettings> UpdateServiceMapServerAsync(string serviceName, MapServerSettings request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(UpdateServiceMapServerAsync),
            async ct => SdkAdminModelMapper.ToServiceSettings(
                await _sdk.UpdateMapServerSettingsAsync(serviceName, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<ServiceSettings> UpdateServiceAccessPolicyAsync(string serviceName, AccessPolicySettings request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(UpdateServiceAccessPolicyAsync),
            async ct => SdkAdminModelMapper.ToServiceSettings(
                await _sdk.UpdateAccessPolicyAsync(serviceName, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<ServiceSettings> UpdateServiceTimeInfoAsync(string serviceName, TimeInfoSettings request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(UpdateServiceTimeInfoAsync),
            async ct => SdkAdminModelMapper.ToServiceSettings(
                await _sdk.UpdateTimeInfoAsync(serviceName, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<LayerMetadataResponse> UpdateServiceLayerMetadataAsync(string serviceName, int layerId, UpdateLayerMetadataRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(UpdateServiceLayerMetadataAsync),
            async ct => SdkAdminModelMapper.ToLayerMetadataResponse(
                await _sdk.UpdateLayerMetadataAsync(serviceName, layerId, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public async Task<IReadOnlyList<MetadataResource>> ListMetadataResourcesAsync(string? kind, string? resourceNamespace, CancellationToken cancellationToken)
        => await ExecuteSdkAsync(
                nameof(ListMetadataResourcesAsync),
                async ct => SdkAdminModelMapper.MapList(
                    await _sdk.ListMetadataResourcesAsync(kind, resourceNamespace, ct).ConfigureAwait(false),
                    SdkAdminModelMapper.ToMetadataResource),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<MetadataResourceResponse> GetMetadataResourceAsync(string kind, string resourceNamespace, string name, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetMetadataResourceAsync),
            async ct =>
            {
                var (resource, eTag) = await _sdk.GetMetadataResourceAsync(kind, resourceNamespace, name, ct).ConfigureAwait(false);
                return new MetadataResourceResponse
                {
                    Resource = SdkAdminModelMapper.ToMetadataResource(resource),
                    ETag = eTag,
                };
            },
            cancellationToken);

    public Task<MetadataResourceResponse> CreateMetadataResourceAsync(MetadataResource resource, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(CreateMetadataResourceAsync),
            async ct => SdkAdminModelMapper.ToMetadataResourceResponse(
                await _sdk.CreateMetadataResourceWithResponseAsync(SdkAdminModelMapper.ToSdk(resource), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<MetadataResourceResponse> UpdateMetadataResourceAsync(
        string kind,
        string resourceNamespace,
        string name,
        MetadataResource resource,
        string ifMatch,
        CancellationToken cancellationToken)
    {
        EnsureIfMatch(ifMatch, nameof(UpdateMetadataResourceAsync));

        return ExecuteSdkAsync(
            nameof(UpdateMetadataResourceAsync),
            async ct => SdkAdminModelMapper.ToMetadataResourceResponse(
                await _sdk.UpdateMetadataResourceWithResponseAsync(
                    kind,
                    resourceNamespace,
                    name,
                    SdkAdminModelMapper.ToSdk(resource),
                    ifMatch,
                    ct).ConfigureAwait(false)),
            cancellationToken);
    }

    public Task DeleteMetadataResourceAsync(
        string kind,
        string resourceNamespace,
        string name,
        string ifMatch,
        CancellationToken cancellationToken)
    {
        EnsureIfMatch(ifMatch, nameof(DeleteMetadataResourceAsync));

        return ExecuteSdkAsync(
            nameof(DeleteMetadataResourceAsync),
            async ct =>
        {
            await _sdk.DeleteMetadataResourceAsync(kind, resourceNamespace, name, ifMatch, ct).ConfigureAwait(false);
        },
            cancellationToken);
    }

    public Task<DeployPreflightResult> GetDeployPreflightAsync(CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetDeployPreflightAsync),
            async ct => SdkAdminModelMapper.ToDeployPreflightResult(await _sdk.GetDeployPreflightAsync(includeDiagnostics: true, ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<DeployPlan> PlanDeployAsync(DeployPlanRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(PlanDeployAsync),
            async ct => SdkAdminModelMapper.ToDeployPlan(
                await _sdk.CreateDeployPlanAsync(SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<DeployOperation> CreateDeployOperationAsync(CreateDeployOperationRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(CreateDeployOperationAsync),
            async ct => SdkAdminModelMapper.ToDeployOperation(
                await _sdk.CreateDeployOperationAsync(SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<DeployOperation> GetDeployOperationAsync(string operationId, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetDeployOperationAsync),
            async ct => SdkAdminModelMapper.ToDeployOperation(await _sdk.GetDeployOperationAsync(operationId, ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<DeployOperation> SubmitDeployOperationAsync(string operationId, SubmitDeployOperationRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(SubmitDeployOperationAsync),
            async ct => SdkAdminModelMapper.ToDeployOperation(
                await _sdk.SubmitDeployOperationAsync(operationId, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<DeployOperation> RollbackDeployOperationAsync(string operationId, RollbackDeployOperationRequest request, CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(RollbackDeployOperationAsync),
            async ct => SdkAdminModelMapper.ToDeployOperation(
                await _sdk.RollbackDeployOperationAsync(operationId, SdkAdminModelMapper.ToSdk(request), ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<ManifestApplyResult> ApplyManifestAsync(ManifestApplyRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(ApplyManifestAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/manifest/apply",
            request,
            TypeInfo<ManifestApplyRequest>(),
            TypeInfo<AdminApiResponse<ManifestApplyResult>>(),
            cancellationToken);

    public Task<ManifestDriftReport> GetManifestDriftAsync(bool verbose, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetManifestDriftAsync),
            $"{ApiVersionPrefix}/manifest/drift?verbose={verbose.ToString().ToLowerInvariant()}",
            TypeInfo<AdminApiResponse<ManifestDriftReport>>(),
            cancellationToken);

    public Task<ManifestVersionListResponse> ListManifestVersionsAsync(int limit, int offset, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(ListManifestVersionsAsync),
            $"{ApiVersionPrefix}/manifest/versions?limit={Math.Clamp(limit, 1, 100)}&offset={Math.Max(0, offset)}",
            TypeInfo<AdminApiResponse<ManifestVersionListResponse>>(),
            cancellationToken);

    public Task<ManifestVersionDetailResponse> GetManifestVersionAsync(string versionId, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetManifestVersionAsync),
            $"{ApiVersionPrefix}/manifest/versions/{Uri.EscapeDataString(versionId)}",
            TypeInfo<AdminApiResponse<ManifestVersionDetailResponse>>(),
            cancellationToken);

    public async Task<IReadOnlyList<ManifestPendingChangeResponse>> ListPendingManifestChangesAsync(string? status, CancellationToken cancellationToken)
        => await GetApiAsync(
                nameof(ListPendingManifestChangesAsync),
                string.IsNullOrWhiteSpace(status)
                    ? $"{ApiVersionPrefix}/manifest/pending/"
                    : $"{ApiVersionPrefix}/manifest/pending/?status={Uri.EscapeDataString(status)}",
                TypeInfo<AdminApiResponse<ManifestPendingChangeResponse[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public async Task<IReadOnlyList<ManifestPendingChangeResponse>> ListManifestApprovalHistoryAsync(CancellationToken cancellationToken)
        => await GetApiAsync(
                nameof(ListManifestApprovalHistoryAsync),
                $"{ApiVersionPrefix}/manifest/pending/history",
                TypeInfo<AdminApiResponse<ManifestPendingChangeResponse[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<ManifestPendingChangeResponse> GetPendingManifestChangeAsync(Guid pendingId, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetPendingManifestChangeAsync),
            $"{ApiVersionPrefix}/manifest/pending/{Uri.EscapeDataString(pendingId.ToString("D"))}",
            TypeInfo<AdminApiResponse<ManifestPendingChangeResponse>>(),
            cancellationToken);

    public Task<ManifestApplyResult> ApprovePendingManifestChangeAsync(Guid pendingId, ManifestApproveRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(ApprovePendingManifestChangeAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/manifest/pending/{Uri.EscapeDataString(pendingId.ToString("D"))}/approve",
            request,
            TypeInfo<ManifestApproveRequest>(),
            TypeInfo<AdminApiResponse<ManifestApplyResult>>(),
            cancellationToken);

    public Task<ManifestPendingChangeResponse> RejectPendingManifestChangeAsync(Guid pendingId, ManifestRejectRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(RejectPendingManifestChangeAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/manifest/pending/{Uri.EscapeDataString(pendingId.ToString("D"))}/reject",
            request,
            TypeInfo<ManifestRejectRequest>(),
            TypeInfo<AdminApiResponse<ManifestPendingChangeResponse>>(),
            cancellationToken);

    public Task<GitOpsWatchConfigResponse> GetGitOpsWatchAsync(CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetGitOpsWatchAsync),
            $"{ApiVersionPrefix}/gitops/watch",
            TypeInfo<AdminApiResponse<GitOpsWatchConfigResponse>>(),
            cancellationToken);

    public Task<GitOpsWatchConfigResponse> ConfigureGitOpsWatchAsync(GitOpsWatchConfigRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(ConfigureGitOpsWatchAsync),
            HttpMethod.Put,
            $"{ApiVersionPrefix}/gitops/watch",
            request,
            TypeInfo<GitOpsWatchConfigRequest>(),
            TypeInfo<AdminApiResponse<GitOpsWatchConfigResponse>>(),
            cancellationToken);

    public async Task DeleteGitOpsWatchAsync(CancellationToken cancellationToken)
    {
        try
        {
            using var response = await _http.DeleteAsync($"{ApiVersionPrefix}/gitops/watch", cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(nameof(DeleteGitOpsWatchAsync), ex.Message);
            throw;
        }
    }

    public async Task<IReadOnlyList<GitOpsChangeRecordResponse>> ListGitOpsChangesAsync(int limit, int offset, CancellationToken cancellationToken)
        => await GetApiAsync(
                nameof(ListGitOpsChangesAsync),
                $"{ApiVersionPrefix}/gitops/changes?limit={Math.Clamp(limit, 1, 100)}&offset={Math.Max(0, offset)}",
                TypeInfo<AdminApiResponse<GitOpsChangeRecordResponse[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<GitOpsChangeRecordResponse> GetGitOpsChangeAsync(Guid changeId, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetGitOpsChangeAsync),
            $"{ApiVersionPrefix}/gitops/changes/{Uri.EscapeDataString(changeId.ToString("D"))}",
            TypeInfo<AdminApiResponse<GitOpsChangeRecordResponse>>(),
            cancellationToken);

    public Task<GitOpsChangeDiffResponse> GetGitOpsChangeDiffAsync(Guid changeId, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetGitOpsChangeDiffAsync),
            $"{ApiVersionPrefix}/gitops/changes/{Uri.EscapeDataString(changeId.ToString("D"))}/diff",
            TypeInfo<AdminApiResponse<GitOpsChangeDiffResponse>>(),
            cancellationToken);

    public Task<RecentErrorsResponse> GetRecentErrorsAsync(CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetRecentErrorsAsync),
            async ct => SdkAdminModelMapper.ToRecentErrorsResponse(await _sdk.GetRecentErrorsResponseAsync(limit: null, ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<ObservabilityStatusResponse> GetTelemetryStatusAsync(CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetTelemetryStatusAsync),
            async ct => SdkAdminModelMapper.ToObservabilityStatusResponse(await _sdk.GetTelemetryStatusAsync(ct).ConfigureAwait(false)),
            cancellationToken);

    public Task<MigrationObservabilityResponse> GetMigrationStatusAsync(CancellationToken cancellationToken)
        => ExecuteSdkAsync(
            nameof(GetMigrationStatusAsync),
            async ct => SdkAdminModelMapper.ToMigrationObservabilityResponse(await _sdk.GetMigrationStatusAsync(ct).ConfigureAwait(false)),
            cancellationToken);

    private static JsonTypeInfo<T> TypeInfo<T>()
        => (JsonTypeInfo<T>)AdminJsonContext.Default.GetTypeInfo(typeof(T))!;

    private async Task ExecuteSdkAsync(
        string operation,
        Func<CancellationToken, Task> action,
        CancellationToken cancellationToken)
    {
        try
        {
            await action(cancellationToken).ConfigureAwait(false);
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
        catch (HonuaAdminApiException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
        catch (HonuaAdminOperationException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private async Task<T> ExecuteSdkAsync<T>(
        string operation,
        Func<CancellationToken, Task<T>> action,
        CancellationToken cancellationToken)
    {
        try
        {
            return await action(cancellationToken).ConfigureAwait(false);
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
        catch (HonuaAdminApiException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
        catch (HonuaAdminOperationException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private async Task<T> GetAsync<T>(string operation, string path, JsonTypeInfo<T> typeInfo, CancellationToken cancellationToken)
    {
        try
        {
            var result = await _http.GetFromJsonAsync(path, typeInfo, cancellationToken).ConfigureAwait(false);
            return result ?? throw new InvalidOperationException($"{operation} returned an empty response.");
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private async Task<T> GetApiAsync<T>(
        string operation,
        string path,
        JsonTypeInfo<AdminApiResponse<T>> typeInfo,
        CancellationToken cancellationToken)
    {
        var envelope = await GetAsync(operation, path, typeInfo, cancellationToken).ConfigureAwait(false);
        return Unwrap(operation, envelope);
    }

    private async Task<TResponse> SendAsync<TRequest, TResponse>(
        string operation,
        HttpMethod method,
        string path,
        TRequest request,
        JsonTypeInfo<TRequest> requestTypeInfo,
        JsonTypeInfo<TResponse> responseTypeInfo,
        CancellationToken cancellationToken)
    {
        try
        {
            using var message = new HttpRequestMessage(method, path)
            {
                Content = new StringContent(
                    JsonSerializer.Serialize(request, requestTypeInfo),
                    Encoding.UTF8,
                    "application/json"),
            };
            using var response = await _http.SendAsync(message, cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
            var result = await response.Content.ReadFromJsonAsync(responseTypeInfo, cancellationToken).ConfigureAwait(false);
            return result ?? throw new InvalidOperationException($"{operation} returned an empty response.");
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private async Task<TResponse> SendApiAsync<TRequest, TResponse>(
        string operation,
        HttpMethod method,
        string path,
        TRequest request,
        JsonTypeInfo<TRequest> requestTypeInfo,
        JsonTypeInfo<AdminApiResponse<TResponse>> responseTypeInfo,
        CancellationToken cancellationToken)
    {
        var envelope = await SendAsync(operation, method, path, request, requestTypeInfo, responseTypeInfo, cancellationToken)
            .ConfigureAwait(false);
        return Unwrap(operation, envelope);
    }

    private static T Unwrap<T>(string operation, AdminApiResponse<T> envelope)
    {
        if (!envelope.Success)
        {
            throw new InvalidOperationException(envelope.Message ?? $"{operation} failed.");
        }

        return envelope.Data ?? throw new InvalidOperationException($"{operation} returned an empty data payload.");
    }

    private static void EnsureIfMatch(string ifMatch, string operation)
    {
        if (string.IsNullOrWhiteSpace(ifMatch))
        {
            throw new ArgumentException($"{operation} requires a non-empty If-Match ETag.", nameof(ifMatch));
        }
    }
}
