// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization.Metadata;
using System.Threading;
using System.Threading.Tasks;
using Honua.Admin.Models.Admin;

namespace Honua.Admin.Services.Admin;

/// <summary>
/// Hand-rolled typed HttpClient implementation of <see cref="IHonuaAdminClient"/>.
/// Authentication and base-URL rebasing live in <c>AdminAuthHandler</c>; 401/CORS
/// handling lives in <c>GlobalErrorHandler</c>.
/// </summary>
public sealed class HonuaAdminClient : IHonuaAdminClient
{
    private const string ApiVersionPrefix = "api/v1/admin";

    private readonly HttpClient _http;
    private readonly IAdminTelemetry _telemetry;

    public HonuaAdminClient(HttpClient http, IAdminTelemetry telemetry)
    {
        _http = http;
        _telemetry = telemetry;
    }

    public Task<FeatureOverview> GetFeatureOverviewAsync(CancellationToken cancellationToken)
        => GetApiAsync(nameof(GetFeatureOverviewAsync), $"{ApiVersionPrefix}/features/", TypeInfo<AdminApiResponse<FeatureOverview>>(), cancellationToken);

    public Task<ConfigurationSummary> GetConfigurationSummaryAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetConfigurationSummaryAsync), $"{ApiVersionPrefix}/configuration/summary", TypeInfo<ConfigurationSummary>(), cancellationToken);

    public Task<ConfigurationDiscoveryResult> DiscoverConfigurationAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(DiscoverConfigurationAsync), $"{ApiVersionPrefix}/configuration/discover", TypeInfo<ConfigurationDiscoveryResult>(), cancellationToken);

    public async Task<IReadOnlyList<ConfigurationMetadata>> GetConfigurationMetadataAsync(CancellationToken cancellationToken)
        => await GetAsync(nameof(GetConfigurationMetadataAsync), $"{ApiVersionPrefix}/configuration/metadata", TypeInfo<ConfigurationMetadata[]>(), cancellationToken)
            .ConfigureAwait(false);

    public async Task<IReadOnlyList<AutoGeneratedDocumentationSection>> GetConfigurationAutoDocumentationAsync(CancellationToken cancellationToken)
        => await GetAsync(nameof(GetConfigurationAutoDocumentationAsync), $"{ApiVersionPrefix}/configuration/auto-documentation", TypeInfo<AutoGeneratedDocumentationSection[]>(), cancellationToken)
            .ConfigureAwait(false);

    public Task<SecretValidationResult> ValidateConfigurationSecretsAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(ValidateConfigurationSecretsAsync), $"{ApiVersionPrefix}/configuration/secrets/validate", TypeInfo<SecretValidationResult>(), cancellationToken);

    public Task<ConfigurationAuditInfo> GetConfigurationAuditInfoAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetConfigurationAuditInfoAsync), $"{ApiVersionPrefix}/configuration/audit", TypeInfo<ConfigurationAuditInfo>(), cancellationToken);

    public Task<JsonElement> GetConfigurationDocumentAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetConfigurationDocumentAsync), $"{ApiVersionPrefix}/config", TypeInfo<JsonElement>(), cancellationToken);

    public Task<JsonElement> GetAdminOpenApiAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetAdminOpenApiAsync), $"{ApiVersionPrefix}/openapi.json", TypeInfo<JsonElement>(), cancellationToken);

    public async Task<IReadOnlyList<ConnectionSummary>> ListConnectionsAsync(CancellationToken cancellationToken)
        => await GetApiAsync(nameof(ListConnectionsAsync), $"{ApiVersionPrefix}/connections/", TypeInfo<AdminApiResponse<ConnectionSummary[]>>(), cancellationToken)
            .ConfigureAwait(false);

    public Task<ConnectionDetail> GetConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => GetApiAsync(nameof(GetConnectionAsync), $"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}", TypeInfo<AdminApiResponse<ConnectionDetail>>(), cancellationToken);

    public Task<ConnectionSummary> CreateConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(CreateConnectionAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/connections/",
            request,
            TypeInfo<CreateConnectionRequest>(),
            TypeInfo<AdminApiResponse<ConnectionSummary>>(),
            cancellationToken);

    public Task<ConnectionSummary> UpdateConnectionAsync(string connectionId, UpdateConnectionRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(UpdateConnectionAsync),
            HttpMethod.Put,
            $"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}",
            request,
            TypeInfo<UpdateConnectionRequest>(),
            TypeInfo<AdminApiResponse<ConnectionSummary>>(),
            cancellationToken);

    public async Task DeleteConnectionAsync(string connectionId, CancellationToken cancellationToken)
    {
        try
        {
            using var response = await _http.DeleteAsync(
                $"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}",
                cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(nameof(DeleteConnectionAsync), ex.Message);
            throw;
        }
    }

    public Task<TestConnectionResult> TestDraftConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(TestDraftConnectionAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/connections/test",
            request,
            TypeInfo<CreateConnectionRequest>(),
            TypeInfo<AdminApiResponse<TestConnectionResult>>(),
            cancellationToken);

    public Task<TestConnectionResult> TestConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => PostEmptyApiAsync<TestConnectionResult>(
            nameof(TestConnectionAsync),
            $"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}/test",
            TypeInfo<AdminApiResponse<TestConnectionResult>>(),
            cancellationToken);

    public Task<EncryptionValidationResult> ValidateEncryptionAsync(CancellationToken cancellationToken)
        => PostEmptyApiAsync<EncryptionValidationResult>(
            nameof(ValidateEncryptionAsync),
            $"{ApiVersionPrefix}/connections/encryption/validate",
            TypeInfo<AdminApiResponse<EncryptionValidationResult>>(),
            cancellationToken);

    public Task<KeyRotationResult> RotateEncryptionKeyAsync(CancellationToken cancellationToken)
        => PostEmptyApiAsync<KeyRotationResult>(
            nameof(RotateEncryptionKeyAsync),
            $"{ApiVersionPrefix}/connections/encryption/rotate-key",
            TypeInfo<AdminApiResponse<KeyRotationResult>>(),
            cancellationToken);

    public async Task<IReadOnlyList<DiscoveredTable>> DiscoverConnectionTablesAsync(string connectionId, CancellationToken cancellationToken)
    {
        var response = await GetAsync(
            nameof(DiscoverConnectionTablesAsync),
            $"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}/tables",
            TypeInfo<TableDiscoveryResponse>(),
            cancellationToken).ConfigureAwait(false);
        return response.Tables;
    }

    public async Task<IReadOnlyList<LayerSummary>> ListLayersAsync(string connectionId, string? serviceName, CancellationToken cancellationToken)
        => await GetApiAsync(
                nameof(ListLayersAsync),
                WithServiceName($"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}/layers/", serviceName),
                TypeInfo<AdminApiResponse<LayerSummary[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<LayerSummary> PublishLayerAsync(string connectionId, PublishLayerRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(PublishLayerAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}/layers/",
            request,
            TypeInfo<PublishLayerRequest>(),
            TypeInfo<AdminApiResponse<LayerSummary>>(),
            cancellationToken);

    public Task<LayerSummary> SetLayerEnabledAsync(string connectionId, int layerId, bool enabled, string? serviceName, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(SetLayerEnabledAsync),
            HttpMethod.Put,
            WithServiceName($"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}/layers/{layerId}/enabled", serviceName),
            new LayerEnabledRequest { Enabled = enabled },
            TypeInfo<LayerEnabledRequest>(),
            TypeInfo<AdminApiResponse<LayerSummary>>(),
            cancellationToken);

    public async Task<IReadOnlyList<LayerSummary>> SetServiceLayersEnabledAsync(string connectionId, bool enabled, string? serviceName, CancellationToken cancellationToken)
        => await SendApiAsync(
                nameof(SetServiceLayersEnabledAsync),
                HttpMethod.Put,
                WithServiceName($"{ApiVersionPrefix}/connections/{Uri.EscapeDataString(connectionId)}/layers/enabled", serviceName),
                new LayerEnabledRequest { Enabled = enabled },
                TypeInfo<LayerEnabledRequest>(),
                TypeInfo<AdminApiResponse<LayerSummary[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<LayerStyle> GetLayerStyleAsync(int layerId, CancellationToken cancellationToken)
        => GetApiAsync(nameof(GetLayerStyleAsync), $"{ApiVersionPrefix}/metadata/layers/{layerId}/style", TypeInfo<AdminApiResponse<LayerStyle>>(), cancellationToken);

    public Task<LayerStyle> UpdateLayerStyleAsync(int layerId, LayerStyleUpdateRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(UpdateLayerStyleAsync),
            HttpMethod.Put,
            $"{ApiVersionPrefix}/metadata/layers/{layerId}/style",
            request,
            TypeInfo<LayerStyleUpdateRequest>(),
            TypeInfo<AdminApiResponse<LayerStyle>>(),
            cancellationToken);

    public async Task<IReadOnlyList<ServiceSummary>> ListServicesAsync(CancellationToken cancellationToken)
        => await GetApiAsync(nameof(ListServicesAsync), $"{ApiVersionPrefix}/services/", TypeInfo<AdminApiResponse<ServiceSummary[]>>(), cancellationToken)
            .ConfigureAwait(false);

    public Task<ServiceSettings> GetServiceSettingsAsync(string serviceName, CancellationToken cancellationToken)
        => GetApiAsync(nameof(GetServiceSettingsAsync), $"{ApiVersionPrefix}/services/{Uri.EscapeDataString(serviceName)}/settings", TypeInfo<AdminApiResponse<ServiceSettings>>(), cancellationToken);

    public Task<ServiceSettings> UpdateServiceProtocolsAsync(string serviceName, UpdateProtocolsRequest request, CancellationToken cancellationToken)
        => SendApiAsync(nameof(UpdateServiceProtocolsAsync), HttpMethod.Put, $"{ApiVersionPrefix}/services/{Uri.EscapeDataString(serviceName)}/protocols", request, TypeInfo<UpdateProtocolsRequest>(), TypeInfo<AdminApiResponse<ServiceSettings>>(), cancellationToken);

    public Task<ServiceSettings> UpdateServiceMapServerAsync(string serviceName, MapServerSettings request, CancellationToken cancellationToken)
        => SendApiAsync(nameof(UpdateServiceMapServerAsync), HttpMethod.Put, $"{ApiVersionPrefix}/services/{Uri.EscapeDataString(serviceName)}/mapserver", request, TypeInfo<MapServerSettings>(), TypeInfo<AdminApiResponse<ServiceSettings>>(), cancellationToken);

    public Task<ServiceSettings> UpdateServiceAccessPolicyAsync(string serviceName, AccessPolicySettings request, CancellationToken cancellationToken)
        => SendApiAsync(nameof(UpdateServiceAccessPolicyAsync), HttpMethod.Put, $"{ApiVersionPrefix}/services/{Uri.EscapeDataString(serviceName)}/access-policy", request, TypeInfo<AccessPolicySettings>(), TypeInfo<AdminApiResponse<ServiceSettings>>(), cancellationToken);

    public Task<ServiceSettings> UpdateServiceTimeInfoAsync(string serviceName, TimeInfoSettings request, CancellationToken cancellationToken)
        => SendApiAsync(nameof(UpdateServiceTimeInfoAsync), HttpMethod.Put, $"{ApiVersionPrefix}/services/{Uri.EscapeDataString(serviceName)}/timeinfo", request, TypeInfo<TimeInfoSettings>(), TypeInfo<AdminApiResponse<ServiceSettings>>(), cancellationToken);

    public Task<LayerMetadataResponse> UpdateServiceLayerMetadataAsync(string serviceName, int layerId, UpdateLayerMetadataRequest request, CancellationToken cancellationToken)
        => SendApiAsync(nameof(UpdateServiceLayerMetadataAsync), HttpMethod.Put, $"{ApiVersionPrefix}/services/{Uri.EscapeDataString(serviceName)}/layers/{layerId}/metadata", request, TypeInfo<UpdateLayerMetadataRequest>(), TypeInfo<AdminApiResponse<LayerMetadataResponse>>(), cancellationToken);

    public async Task<IReadOnlyList<MetadataResource>> ListMetadataResourcesAsync(string? kind, string? resourceNamespace, CancellationToken cancellationToken)
        => await GetApiAsync(
                nameof(ListMetadataResourcesAsync),
                WithMetadataResourceQuery($"{ApiVersionPrefix}/metadata/resources/", kind, resourceNamespace),
                TypeInfo<AdminApiResponse<MetadataResource[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<MetadataResourceResponse> GetMetadataResourceAsync(string kind, string resourceNamespace, string name, CancellationToken cancellationToken)
        => GetMetadataResourceCoreAsync(
            nameof(GetMetadataResourceAsync),
            MetadataResourcePath(kind, resourceNamespace, name),
            cancellationToken);

    public Task<MetadataResourceResponse> CreateMetadataResourceAsync(MetadataResource resource, CancellationToken cancellationToken)
        => SendMetadataResourceAsync(
            nameof(CreateMetadataResourceAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/metadata/resources/",
            resource,
            ifMatch: null,
            cancellationToken);

    public Task<MetadataResourceResponse> UpdateMetadataResourceAsync(
        string kind,
        string resourceNamespace,
        string name,
        MetadataResource resource,
        string ifMatch,
        CancellationToken cancellationToken)
        => SendMetadataResourceAsync(
            nameof(UpdateMetadataResourceAsync),
            HttpMethod.Put,
            MetadataResourcePath(kind, resourceNamespace, name),
            resource,
            ifMatch,
            cancellationToken);

    public async Task DeleteMetadataResourceAsync(
        string kind,
        string resourceNamespace,
        string name,
        string ifMatch,
        CancellationToken cancellationToken)
    {
        try
        {
            using var message = new HttpRequestMessage(HttpMethod.Delete, MetadataResourcePath(kind, resourceNamespace, name));
            message.Headers.TryAddWithoutValidation("If-Match", ifMatch);
            using var response = await _http.SendAsync(message, cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(nameof(DeleteMetadataResourceAsync), ex.Message);
            throw;
        }
    }

    public Task<DeployPreflightResult> GetDeployPreflightAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetDeployPreflightAsync), $"{ApiVersionPrefix}/deploy/preflight?includeDiagnostics=true", TypeInfo<DeployPreflightResult>(), cancellationToken);

    public Task<DeployPlan> PlanDeployAsync(DeployPlanRequest request, CancellationToken cancellationToken)
        => SendAsync(nameof(PlanDeployAsync), HttpMethod.Post, $"{ApiVersionPrefix}/deploy/plan", request, TypeInfo<DeployPlanRequest>(), TypeInfo<DeployPlan>(), cancellationToken);

    public Task<DeployOperation> CreateDeployOperationAsync(CreateDeployOperationRequest request, CancellationToken cancellationToken)
        => SendAsync(nameof(CreateDeployOperationAsync), HttpMethod.Post, $"{ApiVersionPrefix}/deploy/operations", request, TypeInfo<CreateDeployOperationRequest>(), TypeInfo<DeployOperation>(), cancellationToken);

    public Task<DeployOperation> GetDeployOperationAsync(string operationId, CancellationToken cancellationToken)
        => GetAsync(nameof(GetDeployOperationAsync), $"{ApiVersionPrefix}/deploy/operations/{Uri.EscapeDataString(operationId)}", TypeInfo<DeployOperation>(), cancellationToken);

    public Task<DeployOperation> SubmitDeployOperationAsync(string operationId, SubmitDeployOperationRequest request, CancellationToken cancellationToken)
        => SendAsync(nameof(SubmitDeployOperationAsync), HttpMethod.Post, $"{ApiVersionPrefix}/deploy/operations/{Uri.EscapeDataString(operationId)}/submit", request, TypeInfo<SubmitDeployOperationRequest>(), TypeInfo<DeployOperation>(), cancellationToken);

    public Task<DeployOperation> RollbackDeployOperationAsync(string operationId, RollbackDeployOperationRequest request, CancellationToken cancellationToken)
        => SendAsync(nameof(RollbackDeployOperationAsync), HttpMethod.Post, $"{ApiVersionPrefix}/deploy/operations/{Uri.EscapeDataString(operationId)}/rollback", request, TypeInfo<RollbackDeployOperationRequest>(), TypeInfo<DeployOperation>(), cancellationToken);

    public Task<ManifestApplyResult> ApplyManifestAsync(ManifestApplyRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(ApplyManifestAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/manifest/apply",
            request,
            TypeInfo<ManifestApplyRequest>(),
            TypeInfo<AdminApiResponse<ManifestApplyResult>>(),
            cancellationToken);

    public Task<ManifestDriftReport> GetManifestDriftAsync(bool verbose, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetManifestDriftAsync),
            $"{ApiVersionPrefix}/manifest/drift?verbose={verbose.ToString().ToLowerInvariant()}",
            TypeInfo<AdminApiResponse<ManifestDriftReport>>(),
            cancellationToken);

    public Task<ManifestVersionListResponse> ListManifestVersionsAsync(int limit, int offset, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(ListManifestVersionsAsync),
            $"{ApiVersionPrefix}/manifest/versions?limit={Math.Clamp(limit, 1, 100)}&offset={Math.Max(0, offset)}",
            TypeInfo<AdminApiResponse<ManifestVersionListResponse>>(),
            cancellationToken);

    public Task<ManifestVersionDetailResponse> GetManifestVersionAsync(string versionId, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetManifestVersionAsync),
            $"{ApiVersionPrefix}/manifest/versions/{Uri.EscapeDataString(versionId)}",
            TypeInfo<AdminApiResponse<ManifestVersionDetailResponse>>(),
            cancellationToken);

    public async Task<IReadOnlyList<ManifestPendingChangeResponse>> ListPendingManifestChangesAsync(string? status, CancellationToken cancellationToken)
        => await GetApiAsync(
                nameof(ListPendingManifestChangesAsync),
                string.IsNullOrWhiteSpace(status)
                    ? $"{ApiVersionPrefix}/manifest/pending/"
                    : $"{ApiVersionPrefix}/manifest/pending/?status={Uri.EscapeDataString(status)}",
                TypeInfo<AdminApiResponse<ManifestPendingChangeResponse[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public async Task<IReadOnlyList<ManifestPendingChangeResponse>> ListManifestApprovalHistoryAsync(CancellationToken cancellationToken)
        => await GetApiAsync(
                nameof(ListManifestApprovalHistoryAsync),
                $"{ApiVersionPrefix}/manifest/pending/history",
                TypeInfo<AdminApiResponse<ManifestPendingChangeResponse[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<ManifestPendingChangeResponse> GetPendingManifestChangeAsync(Guid pendingId, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetPendingManifestChangeAsync),
            $"{ApiVersionPrefix}/manifest/pending/{Uri.EscapeDataString(pendingId.ToString("D"))}",
            TypeInfo<AdminApiResponse<ManifestPendingChangeResponse>>(),
            cancellationToken);

    public Task<ManifestApplyResult> ApprovePendingManifestChangeAsync(Guid pendingId, ManifestApproveRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(ApprovePendingManifestChangeAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/manifest/pending/{Uri.EscapeDataString(pendingId.ToString("D"))}/approve",
            request,
            TypeInfo<ManifestApproveRequest>(),
            TypeInfo<AdminApiResponse<ManifestApplyResult>>(),
            cancellationToken);

    public Task<ManifestPendingChangeResponse> RejectPendingManifestChangeAsync(Guid pendingId, ManifestRejectRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(RejectPendingManifestChangeAsync),
            HttpMethod.Post,
            $"{ApiVersionPrefix}/manifest/pending/{Uri.EscapeDataString(pendingId.ToString("D"))}/reject",
            request,
            TypeInfo<ManifestRejectRequest>(),
            TypeInfo<AdminApiResponse<ManifestPendingChangeResponse>>(),
            cancellationToken);

    public Task<GitOpsWatchConfigResponse> GetGitOpsWatchAsync(CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetGitOpsWatchAsync),
            $"{ApiVersionPrefix}/gitops/watch",
            TypeInfo<AdminApiResponse<GitOpsWatchConfigResponse>>(),
            cancellationToken);

    public Task<GitOpsWatchConfigResponse> ConfigureGitOpsWatchAsync(GitOpsWatchConfigRequest request, CancellationToken cancellationToken)
        => SendApiAsync(
            nameof(ConfigureGitOpsWatchAsync),
            HttpMethod.Put,
            $"{ApiVersionPrefix}/gitops/watch",
            request,
            TypeInfo<GitOpsWatchConfigRequest>(),
            TypeInfo<AdminApiResponse<GitOpsWatchConfigResponse>>(),
            cancellationToken);

    public async Task DeleteGitOpsWatchAsync(CancellationToken cancellationToken)
    {
        try
        {
            using var response = await _http.DeleteAsync($"{ApiVersionPrefix}/gitops/watch", cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(nameof(DeleteGitOpsWatchAsync), ex.Message);
            throw;
        }
    }

    public async Task<IReadOnlyList<GitOpsChangeRecordResponse>> ListGitOpsChangesAsync(int limit, int offset, CancellationToken cancellationToken)
        => await GetApiAsync(
                nameof(ListGitOpsChangesAsync),
                $"{ApiVersionPrefix}/gitops/changes?limit={Math.Clamp(limit, 1, 100)}&offset={Math.Max(0, offset)}",
                TypeInfo<AdminApiResponse<GitOpsChangeRecordResponse[]>>(),
                cancellationToken)
            .ConfigureAwait(false);

    public Task<GitOpsChangeRecordResponse> GetGitOpsChangeAsync(Guid changeId, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetGitOpsChangeAsync),
            $"{ApiVersionPrefix}/gitops/changes/{Uri.EscapeDataString(changeId.ToString("D"))}",
            TypeInfo<AdminApiResponse<GitOpsChangeRecordResponse>>(),
            cancellationToken);

    public Task<GitOpsChangeDiffResponse> GetGitOpsChangeDiffAsync(Guid changeId, CancellationToken cancellationToken)
        => GetApiAsync(
            nameof(GetGitOpsChangeDiffAsync),
            $"{ApiVersionPrefix}/gitops/changes/{Uri.EscapeDataString(changeId.ToString("D"))}/diff",
            TypeInfo<AdminApiResponse<GitOpsChangeDiffResponse>>(),
            cancellationToken);

    public Task<RecentErrorsResponse> GetRecentErrorsAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetRecentErrorsAsync), $"{ApiVersionPrefix}/observability/errors", TypeInfo<RecentErrorsResponse>(), cancellationToken);

    public Task<ObservabilityStatusResponse> GetTelemetryStatusAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetTelemetryStatusAsync), $"{ApiVersionPrefix}/observability/telemetry", TypeInfo<ObservabilityStatusResponse>(), cancellationToken);

    public Task<MigrationObservabilityResponse> GetMigrationStatusAsync(CancellationToken cancellationToken)
        => GetAsync(nameof(GetMigrationStatusAsync), $"{ApiVersionPrefix}/observability/migrations", TypeInfo<MigrationObservabilityResponse>(), cancellationToken);

    private static JsonTypeInfo<T> TypeInfo<T>()
        => (JsonTypeInfo<T>)AdminJsonContext.Default.GetTypeInfo(typeof(T))!;

    private async Task<T> GetAsync<T>(string operation, string path, JsonTypeInfo<T> typeInfo, CancellationToken cancellationToken)
    {
        try
        {
            var result = await _http.GetFromJsonAsync(path, typeInfo, cancellationToken).ConfigureAwait(false);
            return result ?? throw new InvalidOperationException($"{operation} returned an empty response.");
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private async Task<T> GetApiAsync<T>(
        string operation,
        string path,
        JsonTypeInfo<AdminApiResponse<T>> typeInfo,
        CancellationToken cancellationToken)
    {
        var envelope = await GetAsync(operation, path, typeInfo, cancellationToken).ConfigureAwait(false);
        return Unwrap(operation, envelope);
    }

    private async Task<TResponse> SendAsync<TRequest, TResponse>(
        string operation,
        HttpMethod method,
        string path,
        TRequest request,
        JsonTypeInfo<TRequest> requestTypeInfo,
        JsonTypeInfo<TResponse> responseTypeInfo,
        CancellationToken cancellationToken)
    {
        try
        {
            using var message = new HttpRequestMessage(method, path)
            {
                Content = new StringContent(
                    JsonSerializer.Serialize(request, requestTypeInfo),
                    Encoding.UTF8,
                    "application/json"),
            };
            using var response = await _http.SendAsync(message, cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
            var result = await response.Content.ReadFromJsonAsync(responseTypeInfo, cancellationToken).ConfigureAwait(false);
            return result ?? throw new InvalidOperationException($"{operation} returned an empty response.");
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private async Task<MetadataResourceResponse> GetMetadataResourceCoreAsync(
        string operation,
        string path,
        CancellationToken cancellationToken)
    {
        try
        {
            using var response = await _http.GetAsync(path, cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
            return await ReadMetadataResourceResponseAsync(operation, response, cancellationToken).ConfigureAwait(false);
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private async Task<MetadataResourceResponse> SendMetadataResourceAsync(
        string operation,
        HttpMethod method,
        string path,
        MetadataResource resource,
        string? ifMatch,
        CancellationToken cancellationToken)
    {
        try
        {
            using var message = new HttpRequestMessage(method, path)
            {
                Content = new StringContent(
                    JsonSerializer.Serialize(resource, TypeInfo<MetadataResource>()),
                    Encoding.UTF8,
                    "application/json"),
            };

            if (!string.IsNullOrWhiteSpace(ifMatch))
            {
                message.Headers.TryAddWithoutValidation("If-Match", ifMatch);
            }

            using var response = await _http.SendAsync(message, cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
            return await ReadMetadataResourceResponseAsync(operation, response, cancellationToken).ConfigureAwait(false);
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private static async Task<MetadataResourceResponse> ReadMetadataResourceResponseAsync(
        string operation,
        HttpResponseMessage response,
        CancellationToken cancellationToken)
    {
        var envelope = await response.Content
            .ReadFromJsonAsync(TypeInfo<AdminApiResponse<MetadataResource>>(), cancellationToken)
            .ConfigureAwait(false);
        return new MetadataResourceResponse
        {
            Resource = Unwrap(operation, envelope ?? throw new InvalidOperationException($"{operation} returned an empty response.")),
            ETag = response.Headers.ETag?.ToString(),
        };
    }

    private async Task<TResponse> SendApiAsync<TRequest, TResponse>(
        string operation,
        HttpMethod method,
        string path,
        TRequest request,
        JsonTypeInfo<TRequest> requestTypeInfo,
        JsonTypeInfo<AdminApiResponse<TResponse>> responseTypeInfo,
        CancellationToken cancellationToken)
    {
        var envelope = await SendAsync(operation, method, path, request, requestTypeInfo, responseTypeInfo, cancellationToken)
            .ConfigureAwait(false);
        return Unwrap(operation, envelope);
    }

    private async Task<T> PostEmptyApiAsync<T>(
        string operation,
        string path,
        JsonTypeInfo<AdminApiResponse<T>> responseTypeInfo,
        CancellationToken cancellationToken)
    {
        try
        {
            using var response = await _http.PostAsync(path, content: null, cancellationToken).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
            var envelope = await response.Content.ReadFromJsonAsync(responseTypeInfo, cancellationToken).ConfigureAwait(false);
            return Unwrap(operation, envelope ?? throw new InvalidOperationException($"{operation} returned an empty response."));
        }
        catch (HttpRequestException ex)
        {
            _telemetry.ClientRequestFailed(operation, ex.Message);
            throw;
        }
    }

    private static T Unwrap<T>(string operation, AdminApiResponse<T> envelope)
    {
        if (!envelope.Success)
        {
            throw new InvalidOperationException(envelope.Message ?? $"{operation} failed.");
        }

        return envelope.Data ?? throw new InvalidOperationException($"{operation} returned an empty data payload.");
    }

    private static string WithServiceName(string path, string? serviceName)
        => string.IsNullOrWhiteSpace(serviceName)
            ? path
            : $"{path}?serviceName={Uri.EscapeDataString(serviceName)}";

    private static string MetadataResourcePath(string kind, string resourceNamespace, string name)
        => $"{ApiVersionPrefix}/metadata/resources/{Uri.EscapeDataString(kind)}/{Uri.EscapeDataString(resourceNamespace)}/{Uri.EscapeDataString(name)}";

    private static string WithMetadataResourceQuery(string path, string? kind, string? resourceNamespace)
    {
        var query = new List<string>();
        if (!string.IsNullOrWhiteSpace(kind))
        {
            query.Add($"kind={Uri.EscapeDataString(kind)}");
        }

        if (!string.IsNullOrWhiteSpace(resourceNamespace))
        {
            query.Add($"namespace={Uri.EscapeDataString(resourceNamespace)}");
        }

        return query.Count == 0 ? path : $"{path}?{string.Join("&", query)}";
    }
}
