// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Collections.Generic;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Honua.Admin.Models.Admin;

namespace Honua.Admin.Services.Admin;

/// <summary>
/// Seam between the admin UI and the honua-server admin HTTP surface. Methods
/// are grouped by the P0 endpoint families tracked in
/// <c>docs/admin-ui-api-coverage/coverage.yaml</c>.
/// </summary>
public interface IHonuaAdminClient
{
    Task<FeatureOverview> GetFeatureOverviewAsync(CancellationToken cancellationToken);

    Task<ConfigurationSummary> GetConfigurationSummaryAsync(CancellationToken cancellationToken);
    Task<ConfigurationDiscoveryResult> DiscoverConfigurationAsync(CancellationToken cancellationToken);
    Task<IReadOnlyList<ConfigurationMetadata>> GetConfigurationMetadataAsync(CancellationToken cancellationToken);
    Task<IReadOnlyList<AutoGeneratedDocumentationSection>> GetConfigurationAutoDocumentationAsync(CancellationToken cancellationToken);
    Task<SecretValidationResult> ValidateConfigurationSecretsAsync(CancellationToken cancellationToken);
    Task<ConfigurationAuditInfo> GetConfigurationAuditInfoAsync(CancellationToken cancellationToken);
    Task<JsonElement> GetConfigurationDocumentAsync(CancellationToken cancellationToken);
    Task<JsonElement> GetAdminOpenApiAsync(CancellationToken cancellationToken);

    Task<IReadOnlyList<ConnectionSummary>> ListConnectionsAsync(CancellationToken cancellationToken);
    Task<ConnectionDetail> GetConnectionAsync(string connectionId, CancellationToken cancellationToken);
    Task<ConnectionSummary> CreateConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken);
    Task<ConnectionSummary> UpdateConnectionAsync(string connectionId, UpdateConnectionRequest request, CancellationToken cancellationToken);
    Task DeleteConnectionAsync(string connectionId, CancellationToken cancellationToken);
    Task<TestConnectionResult> TestDraftConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken);
    Task<TestConnectionResult> TestConnectionAsync(string connectionId, CancellationToken cancellationToken);
    Task<EncryptionValidationResult> ValidateEncryptionAsync(CancellationToken cancellationToken);
    Task<KeyRotationResult> RotateEncryptionKeyAsync(CancellationToken cancellationToken);
    Task<IReadOnlyList<DiscoveredTable>> DiscoverConnectionTablesAsync(string connectionId, CancellationToken cancellationToken);

    Task<IReadOnlyList<LayerSummary>> ListLayersAsync(string connectionId, string? serviceName, CancellationToken cancellationToken);
    Task<LayerSummary> PublishLayerAsync(string connectionId, PublishLayerRequest request, CancellationToken cancellationToken);
    Task<LayerSummary> SetLayerEnabledAsync(string connectionId, int layerId, bool enabled, string? serviceName, CancellationToken cancellationToken);
    Task<IReadOnlyList<LayerSummary>> SetServiceLayersEnabledAsync(string connectionId, bool enabled, string? serviceName, CancellationToken cancellationToken);
    Task<LayerStyle> GetLayerStyleAsync(int layerId, CancellationToken cancellationToken);
    Task<LayerStyle> UpdateLayerStyleAsync(int layerId, LayerStyleUpdateRequest request, CancellationToken cancellationToken);

    Task<IReadOnlyList<ServiceSummary>> ListServicesAsync(CancellationToken cancellationToken);
    Task<ServiceSettings> GetServiceSettingsAsync(string serviceName, CancellationToken cancellationToken);
    Task<ServiceSettings> UpdateServiceProtocolsAsync(string serviceName, UpdateProtocolsRequest request, CancellationToken cancellationToken);
    Task<ServiceSettings> UpdateServiceMapServerAsync(string serviceName, MapServerSettings request, CancellationToken cancellationToken);
    Task<ServiceSettings> UpdateServiceAccessPolicyAsync(string serviceName, AccessPolicySettings request, CancellationToken cancellationToken);
    Task<ServiceSettings> UpdateServiceTimeInfoAsync(string serviceName, TimeInfoSettings request, CancellationToken cancellationToken);
    Task<LayerMetadataResponse> UpdateServiceLayerMetadataAsync(string serviceName, int layerId, UpdateLayerMetadataRequest request, CancellationToken cancellationToken);

    Task<DeployPreflightResult> GetDeployPreflightAsync(CancellationToken cancellationToken);
    Task<DeployPlan> PlanDeployAsync(DeployPlanRequest request, CancellationToken cancellationToken);
    Task<DeployOperation> CreateDeployOperationAsync(CreateDeployOperationRequest request, CancellationToken cancellationToken);
    Task<DeployOperation> GetDeployOperationAsync(string operationId, CancellationToken cancellationToken);
    Task<DeployOperation> SubmitDeployOperationAsync(string operationId, SubmitDeployOperationRequest request, CancellationToken cancellationToken);
    Task<DeployOperation> RollbackDeployOperationAsync(string operationId, RollbackDeployOperationRequest request, CancellationToken cancellationToken);

    Task<RecentErrorsResponse> GetRecentErrorsAsync(CancellationToken cancellationToken);
    Task<ObservabilityStatusResponse> GetTelemetryStatusAsync(CancellationToken cancellationToken);
    Task<MigrationObservabilityResponse> GetMigrationStatusAsync(CancellationToken cancellationToken);
}
