// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Honua.Admin.Models.Admin;

namespace Honua.Admin.Services.Admin;

/// <summary>
/// Deterministic in-memory stub for unit tests and the dev shell. Mirrors the
/// <c>StubSpecWorkspaceClient</c> pattern.
/// </summary>
public class StubHonuaAdminClient : IHonuaAdminClient
{
    public static readonly Guid PrimaryConnectionId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");

    public FeatureOverview FeatureOverview { get; init; } = new()
    {
        CurrentEdition = "Enterprise",
        Features =
        [
            new FeatureOverviewItem { Key = "ogc-features", DisplayName = "OGC Features", Category = "Protocol", Description = "OGC API Features support", IsEnabled = true, MinimumEdition = "Community" },
            new FeatureOverviewItem { Key = "tiles", DisplayName = "Tiles", Category = "Protocol", Description = "Vector and raster tile serving", IsEnabled = true, MinimumEdition = "Enterprise" },
            new FeatureOverviewItem { Key = "advanced-observability", DisplayName = "Advanced Observability", Category = "Operations", Description = "Expanded telemetry and alerting", IsEnabled = false, MinimumEdition = "EnterprisePlus", UpgradeMessage = "Requires EnterprisePlus" },
        ],
    };

    public ConfigurationSummary ConfigurationSummary { get; init; } = new()
    {
        TotalTypes = 18,
        RegisteredTypes = 18,
        TotalProperties = 96,
        SecretProperties = 7,
        RequiredProperties = 9,
        TypesWithValidation = 13,
        TotalSecrets = 3,
        ValidSecrets = 3,
        InvalidSecrets = 0,
        Environment = "Development",
        DiscoveryDurationMs = 12,
        LastDiscovery = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public ConfigurationDiscoveryResult ConfigurationDiscovery { get; init; } = new()
    {
        DiscoveredTypes =
        [
            new ConfigurationTypeInfo
            {
                SectionName = "Honua:Database",
                TypeName = "DatabaseOptions",
                FullTypeName = "Honua.Core.Configuration.DatabaseOptions",
                Assembly = "Honua.Core",
                IsRegisteredInDi = true,
                Properties =
                [
                    new PropertyMetadata { Name = "ConnectionString", Type = "String", IsRequired = true, IsSecret = true },
                    new PropertyMetadata { Name = "CommandTimeoutSeconds", Type = "Int32", IsRequired = false, IsSecret = false },
                ],
            },
        ],
        ExtractedMetadata =
        [
            new ConfigurationMetadata { SectionName = "Honua:Database", TypeName = "DatabaseOptions", PropertyCount = 2, SecretPropertyCount = 1, RequiredPropertyCount = 1, HasValidation = true, IsRegistered = true },
        ],
        AutoGeneratedDocumentation =
        [
            new AutoGeneratedDocumentationSection { SectionName = "Honua:Database", TypeName = "DatabaseOptions", Description = "Database connectivity settings" },
        ],
        SecretValidation = new SecretValidationResult { TotalSecrets = 3, ValidSecrets = 3, InvalidSecrets = 0 },
        AuditInformation = new ConfigurationAuditInfo
        {
            Environment = "Development",
            MachineName = "stub-host",
            ApplicationName = "Honua.Server",
            ContentRoot = "/app",
            ConfigurationSources = new Dictionary<string, int> { ["appsettings.json"] = 24 },
            TotalConfigurationKeys = 24,
        },
        DiscoveryDurationMs = 12,
        Timestamp = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public IReadOnlyList<ConnectionSummary> Connections { get; init; } =
    [
        new ConnectionSummary
        {
            ConnectionId = PrimaryConnectionId,
            Name = "primary-postgis",
            Description = "Primary spatial warehouse",
            Host = "db.local",
            Port = 5432,
            DatabaseName = "honua",
            Username = "honua_admin",
            SslRequired = true,
            SslMode = "Require",
            StorageType = "managed",
            IsActive = true,
            HealthStatus = "Healthy",
            CreatedAt = DateTimeOffset.Parse("2026-04-01T00:00:00Z"),
            CreatedBy = "admin",
        },
    ];

    public ConnectionDetail ConnectionDetail { get; init; } = new()
    {
        ConnectionId = PrimaryConnectionId,
        Name = "primary-postgis",
        Description = "Primary spatial warehouse",
        Host = "db.local",
        Port = 5432,
        DatabaseName = "honua",
        Username = "honua_admin",
        SslRequired = true,
        SslMode = "Require",
        StorageType = "managed",
        IsActive = true,
        HealthStatus = "Healthy",
        CreatedAt = DateTimeOffset.Parse("2026-04-01T00:00:00Z"),
        CreatedBy = "admin",
        EncryptionVersion = 3,
        UpdatedAt = DateTimeOffset.Parse("2026-04-20T00:00:00Z"),
    };

    public IReadOnlyList<DiscoveredTable> Tables { get; init; } =
    [
        new DiscoveredTable { Schema = "public", Table = "parcels", GeometryColumn = "geom", GeometryType = "Polygon", Srid = 4326, EstimatedRows = 1250 },
    ];

    public IReadOnlyList<LayerSummary> Layers { get; init; } =
    [
        new LayerSummary { LayerId = 101, LayerName = "Parcels", Schema = "public", Table = "parcels", GeometryType = "Polygon", Srid = 4326, FieldCount = 12, Enabled = true, ServiceName = "default" },
    ];

    public LayerStyle LayerStyle { get; init; } = new()
    {
        MapLibreStyle = Json("""{"version":8,"layers":[]}"""),
        DrawingInfo = Json("""{"renderer":{"type":"simple"}}"""),
    };

    public IReadOnlyList<ServiceSummary> Services { get; init; } =
    [
        new ServiceSummary { ServiceName = "default", Description = "Default feature service", LayerCount = 1, EnabledProtocols = ["FeatureServer", "OgcFeatures"] },
    ];

    public ServiceSettings ServiceSettings { get; init; } = new()
    {
        ServiceName = "default",
        EnabledProtocols = ["FeatureServer", "OgcFeatures"],
        AvailableProtocols = ["FeatureServer", "MapServer", "OgcFeatures", "OData", "Grpc"],
        AccessPolicy = new AccessPolicySettings { AllowAnonymous = true, AllowAnonymousWrite = false, AllowedRoles = ["operator"], AllowedWriteRoles = ["admin"] },
        TimeInfo = new TimeInfoSettings { StartTimeField = "valid_from", EndTimeField = "valid_to" },
        MapServer = new MapServerSettings { MaxImageWidth = 4096, MaxImageHeight = 4096, DefaultImageWidth = 1024, DefaultImageHeight = 768, DefaultDpi = 96, DefaultFormat = "png", DefaultTransparent = true, MaxFeaturesPerLayer = 1000 },
    };

    public DeployPreflightResult DeployPreflight { get; init; } = new()
    {
        Status = "ready",
        ReadyForCoordinatedDeploy = true,
        Message = "Instance is ready for coordinated deployment.",
        ServerVersion = "1.0.0",
        Environment = "Development",
        DeploymentMode = "Standalone",
        InstanceName = "stub-host",
        GeneratedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public DeployPlan DeployPlan { get; init; } = new()
    {
        Target = new DeployPlanTarget { TargetId = "honua-server", TargetName = "Honua Server", TargetKind = "Service", Backend = "stub", Environment = "dev", DesiredRevision = "rev-2", CurrentRevision = "rev-1" },
        ReadyToSubmit = true,
        BackendRegistered = true,
        GeneratedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public DeployOperation DeployOperation { get; init; } = new()
    {
        OperationId = "op-1",
        Kind = "Deploy",
        Status = "AwaitingApproval",
        Priority = "Normal",
        Target = new DeployPlanTarget { TargetId = "honua-server", TargetName = "Honua Server", TargetKind = "Service", Backend = "stub", Environment = "dev", DesiredRevision = "rev-2" },
        CreatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
        UpdatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public ManifestDriftReport ManifestDrift { get; init; } = new()
    {
        GeneratedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
        BaselineVersionId = "manifest-v2",
        HasDrift = true,
        Resources =
        [
            new ManifestDriftRecord
            {
                Identifier = new MetadataResourceIdentifier { Kind = "service", Namespace = "default", Name = "parcels" },
                DriftType = "spec-drift",
                DeclaredHash = "sha256:desired",
                ActualHash = "sha256:actual",
            },
        ],
    };

    public ManifestVersionListResponse ManifestVersions { get; init; } = new()
    {
        Versions =
        [
            new ManifestVersionResponse
            {
                VersionId = "manifest-v2",
                ManifestHash = "sha256:desired",
                Summary = "Promote parcels publishing intent",
                Actor = "admin",
                AppliedAt = DateTimeOffset.Parse("2026-04-24T00:00:00Z"),
                ResourceCount = 3,
            },
        ],
    };

    public ManifestVersionDetailResponse ManifestVersionDetail { get; init; } = new()
    {
        VersionId = "manifest-v2",
        ManifestHash = "sha256:desired",
        Summary = "Promote parcels publishing intent",
        Actor = "admin",
        AppliedAt = DateTimeOffset.Parse("2026-04-24T00:00:00Z"),
        ResourceCount = 3,
        Manifest = Json("""{"apiVersion":"admin.honua.io/v1","resources":[]}"""),
    };

    public IReadOnlyList<ManifestPendingChangeResponse> ManifestPendingChanges { get; init; } =
    [
        new ManifestPendingChangeResponse
        {
            PendingId = Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
            ManifestHash = "sha256:pending",
            Status = "pending",
            RequestedBy = "gitops",
            RequestedReason = "Promote staging manifest",
            ResourceCount = 2,
            DryRun = false,
            Prune = false,
            CreatedAt = DateTimeOffset.Parse("2026-04-25T01:00:00Z"),
            ExpiresAt = DateTimeOffset.Parse("2026-04-26T01:00:00Z"),
        },
    ];

    public IReadOnlyList<ManifestPendingChangeResponse> ManifestApprovalHistory { get; init; } =
    [
        new ManifestPendingChangeResponse
        {
            PendingId = Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccccc"),
            ManifestHash = "sha256:approved",
            Status = "approved",
            RequestedBy = "gitops",
            RequestedReason = "Promote dev manifest",
            DecisionBy = "admin",
            DecisionReason = "validated",
            ResourceCount = 4,
            DryRun = false,
            Prune = true,
            CreatedAt = DateTimeOffset.Parse("2026-04-23T01:00:00Z"),
            DecidedAt = DateTimeOffset.Parse("2026-04-23T02:00:00Z"),
        },
    ];

    public GitOpsWatchConfigResponse GitOpsWatch { get; init; } = new()
    {
        ConfigId = Guid.Parse("dddddddd-dddd-dddd-dddd-dddddddddddd"),
        RepositoryUrl = "https://github.com/honua-io/honua-env",
        Branch = "main",
        ManifestPath = "environments/dev",
        PollIntervalSeconds = 60,
        ApprovalRequired = true,
        PruneEnabled = false,
        Enabled = true,
        LastKnownCommitSha = "0123456789abcdef0123456789abcdef01234567",
        LastPolledAt = DateTimeOffset.Parse("2026-04-25T02:00:00Z"),
        ConfiguredBy = "admin",
        CreatedAt = DateTimeOffset.Parse("2026-04-20T00:00:00Z"),
        UpdatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public IReadOnlyList<GitOpsChangeRecordResponse> GitOpsChanges { get; init; } =
    [
        new GitOpsChangeRecordResponse
        {
            ChangeId = Guid.Parse("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
            ConfigId = Guid.Parse("dddddddd-dddd-dddd-dddd-dddddddddddd"),
            CommitSha = "0123456789abcdef0123456789abcdef01234567",
            CommitMessage = "Promote parcels service",
            CommitAuthor = "ops",
            CommitTimestamp = DateTimeOffset.Parse("2026-04-25T01:30:00Z"),
            Status = "pending_approval",
            PendingApprovalId = Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
            DetectedAt = DateTimeOffset.Parse("2026-04-25T01:31:00Z"),
        },
    ];

    public GitOpsChangeDiffResponse GitOpsChangeDiff { get; init; } = new()
    {
        ChangeId = Guid.Parse("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
        CommitSha = "0123456789abcdef0123456789abcdef01234567",
        Before = Json("""{"resources":[]}"""),
        After = Json("""{"resources":[{"kind":"service"}]}"""),
    };

    public IReadOnlyList<MetadataResource> MetadataResources { get; init; } =
    [
        new MetadataResource
        {
            ApiVersion = "honua.io/v1alpha1",
            Kind = "Layer",
            Metadata = new ResourceMetadata
            {
                Name = "parcels",
                Namespace = "default",
                ResourceVersion = "1",
            },
            Spec = Json("""{"schemaName":"public","tableName":"parcels","geometryType":"Polygon","srid":4326}"""),
        },
    ];

    public RecentErrorsResponse RecentErrors { get; init; } = new()
    {
        Capacity = 50,
        InstanceId = "stub-host-1",
        Errors =
        [
            new RecentErrorEntry { Timestamp = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), CorrelationId = "corr-1", Path = "/api/v1/admin/services", StatusCode = 500, Message = "Sample recent error" },
        ],
    };

    public ObservabilityStatusResponse TelemetryStatus { get; init; } = new()
    {
        TracingEnabled = true,
        OtlpConfigured = true,
        OtlpEndpoint = "http://collector:4317",
    };

    public MigrationObservabilityResponse MigrationStatus { get; init; } = new()
    {
        Status = "succeeded",
        IsReady = true,
        PlanAvailable = true,
        UpgradeRequired = false,
        GeneratedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public virtual Task<FeatureOverview> GetFeatureOverviewAsync(CancellationToken cancellationToken)
        => Task.FromResult(FeatureOverview);

    public virtual Task<ConfigurationSummary> GetConfigurationSummaryAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationSummary);

    public virtual Task<ConfigurationDiscoveryResult> DiscoverConfigurationAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery);

    public virtual Task<IReadOnlyList<ConfigurationMetadata>> GetConfigurationMetadataAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery.ExtractedMetadata);

    public virtual Task<IReadOnlyList<AutoGeneratedDocumentationSection>> GetConfigurationAutoDocumentationAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery.AutoGeneratedDocumentation);

    public virtual Task<SecretValidationResult> ValidateConfigurationSecretsAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery.SecretValidation);

    public virtual Task<ConfigurationAuditInfo> GetConfigurationAuditInfoAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery.AuditInformation);

    public virtual Task<JsonElement> GetConfigurationDocumentAsync(CancellationToken cancellationToken)
        => Task.FromResult(Json("""{"sections":[{"name":"Honua"}]}"""));

    public virtual Task<JsonElement> GetAdminOpenApiAsync(CancellationToken cancellationToken)
        => Task.FromResult(Json("""{"openapi":"3.0.3","paths":{}}"""));

    public virtual Task<IReadOnlyList<ConnectionSummary>> ListConnectionsAsync(CancellationToken cancellationToken)
        => Task.FromResult(Connections);

    public virtual Task<ConnectionDetail> GetConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => Task.FromResult(ConnectionDetail);

    public virtual Task<ConnectionSummary> CreateConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken)
        => Task.FromResult(Connections[0]);

    public virtual Task<ConnectionSummary> UpdateConnectionAsync(string connectionId, UpdateConnectionRequest request, CancellationToken cancellationToken)
        => Task.FromResult(Connections[0]);

    public virtual Task DeleteConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => Task.CompletedTask;

    public virtual Task<TestConnectionResult> TestDraftConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken)
        => Task.FromResult(new TestConnectionResult { ConnectionName = request.Name, IsHealthy = true, TestedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), Message = "Connection is healthy" });

    public virtual Task<TestConnectionResult> TestConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => Task.FromResult(new TestConnectionResult { ConnectionId = PrimaryConnectionId, ConnectionName = "primary-postgis", IsHealthy = true, TestedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), Message = "Connection is healthy" });

    public virtual Task<EncryptionValidationResult> ValidateEncryptionAsync(CancellationToken cancellationToken)
        => Task.FromResult(new EncryptionValidationResult { IsValid = true, CurrentKeyVersion = 3, ValidatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), Message = "Encryption service is working correctly" });

    public virtual Task<KeyRotationResult> RotateEncryptionKeyAsync(CancellationToken cancellationToken)
        => Task.FromResult(new KeyRotationResult { PreviousKeyVersion = 3, NewKeyVersion = 4, RotatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), Message = "Encryption key rotated successfully" });

    public virtual Task<IReadOnlyList<DiscoveredTable>> DiscoverConnectionTablesAsync(string connectionId, CancellationToken cancellationToken)
        => Task.FromResult(Tables);

    public virtual Task<IReadOnlyList<LayerSummary>> ListLayersAsync(string connectionId, string? serviceName, CancellationToken cancellationToken)
        => Task.FromResult(Layers);

    public virtual Task<LayerSummary> PublishLayerAsync(string connectionId, PublishLayerRequest request, CancellationToken cancellationToken)
        => Task.FromResult(Layers[0]);

    public virtual Task<LayerSummary> SetLayerEnabledAsync(string connectionId, int layerId, bool enabled, string? serviceName, CancellationToken cancellationToken)
        => Task.FromResult(Layers[0] with { Enabled = enabled });

    public virtual Task<IReadOnlyList<LayerSummary>> SetServiceLayersEnabledAsync(string connectionId, bool enabled, string? serviceName, CancellationToken cancellationToken)
        => Task.FromResult<IReadOnlyList<LayerSummary>>([.. Layers.Select(layer => layer with { Enabled = enabled })]);

    public virtual Task<LayerStyle> GetLayerStyleAsync(int layerId, CancellationToken cancellationToken)
        => Task.FromResult(LayerStyle);

    public virtual Task<LayerStyle> UpdateLayerStyleAsync(int layerId, LayerStyleUpdateRequest request, CancellationToken cancellationToken)
        => Task.FromResult(new LayerStyle { MapLibreStyle = request.MapLibreStyle, DrawingInfo = request.DrawingInfo });

    public virtual Task<IReadOnlyList<ServiceSummary>> ListServicesAsync(CancellationToken cancellationToken)
        => Task.FromResult(Services);

    public virtual Task<ServiceSettings> GetServiceSettingsAsync(string serviceName, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings);

    public virtual Task<ServiceSettings> UpdateServiceProtocolsAsync(string serviceName, UpdateProtocolsRequest request, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings with { EnabledProtocols = request.EnabledProtocols });

    public virtual Task<ServiceSettings> UpdateServiceMapServerAsync(string serviceName, MapServerSettings request, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings with { MapServer = request });

    public virtual Task<ServiceSettings> UpdateServiceAccessPolicyAsync(string serviceName, AccessPolicySettings request, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings with { AccessPolicy = request });

    public virtual Task<ServiceSettings> UpdateServiceTimeInfoAsync(string serviceName, TimeInfoSettings request, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings with { TimeInfo = request });

    public virtual Task<LayerMetadataResponse> UpdateServiceLayerMetadataAsync(string serviceName, int layerId, UpdateLayerMetadataRequest request, CancellationToken cancellationToken)
        => Task.FromResult(new LayerMetadataResponse { LayerId = layerId, LayerName = "Parcels", AccessPolicy = request.AccessPolicy, TimeInfo = request.TimeInfo });

    public virtual Task<IReadOnlyList<MetadataResource>> ListMetadataResourcesAsync(string? kind, string? resourceNamespace, CancellationToken cancellationToken)
        => Task.FromResult<IReadOnlyList<MetadataResource>>(
            [.. MetadataResources.Where(resource =>
                (string.IsNullOrWhiteSpace(kind) || string.Equals(resource.Kind, kind, StringComparison.OrdinalIgnoreCase)) &&
                (string.IsNullOrWhiteSpace(resourceNamespace) || string.Equals(resource.Metadata?.Namespace, resourceNamespace, StringComparison.OrdinalIgnoreCase)))]);

    public virtual Task<MetadataResourceResponse> GetMetadataResourceAsync(string kind, string resourceNamespace, string name, CancellationToken cancellationToken)
    {
        var resource = MetadataResources.FirstOrDefault(candidate =>
            string.Equals(candidate.Kind, kind, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(candidate.Metadata?.Namespace, resourceNamespace, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(candidate.Metadata?.Name, name, StringComparison.OrdinalIgnoreCase)) ?? MetadataResources[0];
        return Task.FromResult(new MetadataResourceResponse { Resource = resource, ETag = "\"stub-metadata-etag\"" });
    }

    public virtual Task<MetadataResourceResponse> CreateMetadataResourceAsync(MetadataResource resource, CancellationToken cancellationToken)
        => Task.FromResult(new MetadataResourceResponse
        {
            Resource = resource with { Metadata = (resource.Metadata ?? new ResourceMetadata()) with { ResourceVersion = "1" } },
            ETag = "\"stub-metadata-etag-1\"",
        });

    public virtual Task<MetadataResourceResponse> UpdateMetadataResourceAsync(string kind, string resourceNamespace, string name, MetadataResource resource, string ifMatch, CancellationToken cancellationToken)
        => Task.FromResult(new MetadataResourceResponse
        {
            Resource = resource with
            {
                Kind = kind,
                Metadata = (resource.Metadata ?? new ResourceMetadata()) with
                {
                    Name = name,
                    Namespace = resourceNamespace,
                    ResourceVersion = "2",
                },
            },
            ETag = "\"stub-metadata-etag-2\"",
        });

    public virtual Task DeleteMetadataResourceAsync(string kind, string resourceNamespace, string name, string ifMatch, CancellationToken cancellationToken)
        => Task.CompletedTask;

    public virtual Task<DeployPreflightResult> GetDeployPreflightAsync(CancellationToken cancellationToken)
        => Task.FromResult(DeployPreflight);

    public virtual Task<DeployPlan> PlanDeployAsync(DeployPlanRequest request, CancellationToken cancellationToken)
        => Task.FromResult(DeployPlan with { Target = DeployPlan.Target with { TargetId = request.TargetId, DesiredRevision = request.DesiredRevision, CurrentRevision = request.CurrentRevision } });

    public virtual Task<DeployOperation> CreateDeployOperationAsync(CreateDeployOperationRequest request, CancellationToken cancellationToken)
        => Task.FromResult(DeployOperation);

    public virtual Task<DeployOperation> GetDeployOperationAsync(string operationId, CancellationToken cancellationToken)
        => Task.FromResult(DeployOperation with { OperationId = operationId });

    public virtual Task<DeployOperation> SubmitDeployOperationAsync(string operationId, SubmitDeployOperationRequest request, CancellationToken cancellationToken)
        => Task.FromResult(DeployOperation with { OperationId = operationId, Status = "Submitted", Reason = request.Reason });

    public virtual Task<DeployOperation> RollbackDeployOperationAsync(string operationId, RollbackDeployOperationRequest request, CancellationToken cancellationToken)
        => Task.FromResult(DeployOperation with { OperationId = operationId, Status = "RollbackRequested", Reason = request.Reason });

    public virtual Task<ManifestApplyResult> ApplyManifestAsync(ManifestApplyRequest request, CancellationToken cancellationToken)
        => Task.FromResult(new ManifestApplyResult
        {
            DryRun = request.DryRun,
            Summary = new ManifestApplySummary
            {
                Created = request.Resources.Count,
                Updated = 0,
                Deleted = 0,
                Skipped = 0,
            },
            Entries =
            [
                .. request.Resources.Select(resource => new ManifestApplyEntry
                {
                    Action = "create",
                    Resource = new MetadataResourceIdentifier
                    {
                        Kind = resource.Kind ?? string.Empty,
                        Namespace = resource.Metadata?.Namespace ?? "default",
                        Name = resource.Metadata?.Name ?? string.Empty,
                    },
                }),
            ],
        });

    public virtual Task<ManifestDriftReport> GetManifestDriftAsync(bool verbose, CancellationToken cancellationToken)
        => Task.FromResult(ManifestDrift);

    public virtual Task<ManifestVersionListResponse> ListManifestVersionsAsync(int limit, int offset, CancellationToken cancellationToken)
        => Task.FromResult(ManifestVersions);

    public virtual Task<ManifestVersionDetailResponse> GetManifestVersionAsync(string versionId, CancellationToken cancellationToken)
        => Task.FromResult(ManifestVersionDetail with { VersionId = versionId });

    public virtual Task<IReadOnlyList<ManifestPendingChangeResponse>> ListPendingManifestChangesAsync(string? status, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(status))
        {
            return Task.FromResult(ManifestPendingChanges);
        }

        return Task.FromResult<IReadOnlyList<ManifestPendingChangeResponse>>(
            [.. ManifestPendingChanges.Where(change => string.Equals(change.Status, status, StringComparison.OrdinalIgnoreCase))]);
    }

    public virtual Task<IReadOnlyList<ManifestPendingChangeResponse>> ListManifestApprovalHistoryAsync(CancellationToken cancellationToken)
        => Task.FromResult(ManifestApprovalHistory);

    public virtual Task<ManifestPendingChangeResponse> GetPendingManifestChangeAsync(Guid pendingId, CancellationToken cancellationToken)
        => Task.FromResult(ManifestPendingChanges.FirstOrDefault(change => change.PendingId == pendingId) ?? (ManifestPendingChanges[0] with { PendingId = pendingId }));

    public virtual Task<ManifestApplyResult> ApprovePendingManifestChangeAsync(Guid pendingId, ManifestApproveRequest request, CancellationToken cancellationToken)
        => Task.FromResult(new ManifestApplyResult
        {
            DryRun = false,
            Summary = new ManifestApplySummary { Created = 1, Updated = 1, Deleted = 0, Skipped = 0 },
            Entries =
            [
                new ManifestApplyEntry
                {
                    Action = "update",
                    Resource = new MetadataResourceIdentifier { Kind = "service", Namespace = "default", Name = "parcels" },
                    Message = request.Reason,
                },
            ],
        });

    public virtual Task<ManifestPendingChangeResponse> RejectPendingManifestChangeAsync(Guid pendingId, ManifestRejectRequest request, CancellationToken cancellationToken)
        => Task.FromResult((ManifestPendingChanges.FirstOrDefault(change => change.PendingId == pendingId) ?? ManifestPendingChanges[0]) with
        {
            Status = "rejected",
            DecisionBy = request.RejectedBy,
            DecisionReason = request.Reason,
            DecidedAt = DateTimeOffset.Parse("2026-04-25T02:00:00Z"),
        });

    public virtual Task<GitOpsWatchConfigResponse> GetGitOpsWatchAsync(CancellationToken cancellationToken)
        => Task.FromResult(GitOpsWatch);

    public virtual Task<GitOpsWatchConfigResponse> ConfigureGitOpsWatchAsync(GitOpsWatchConfigRequest request, CancellationToken cancellationToken)
        => Task.FromResult(GitOpsWatch with
        {
            RepositoryUrl = request.RepositoryUrl,
            Branch = request.Branch,
            ManifestPath = request.ManifestPath,
            PollIntervalSeconds = request.PollIntervalSeconds,
            ApprovalRequired = request.ApprovalRequired,
            PruneEnabled = request.PruneEnabled,
            Enabled = request.Enabled,
            ConfiguredBy = request.ConfiguredBy,
        });

    public virtual Task DeleteGitOpsWatchAsync(CancellationToken cancellationToken)
        => Task.CompletedTask;

    public virtual Task<IReadOnlyList<GitOpsChangeRecordResponse>> ListGitOpsChangesAsync(int limit, int offset, CancellationToken cancellationToken)
        => Task.FromResult(GitOpsChanges);

    public virtual Task<GitOpsChangeRecordResponse> GetGitOpsChangeAsync(Guid changeId, CancellationToken cancellationToken)
        => Task.FromResult(GitOpsChanges.FirstOrDefault(change => change.ChangeId == changeId) ?? (GitOpsChanges[0] with { ChangeId = changeId }));

    public virtual Task<GitOpsChangeDiffResponse> GetGitOpsChangeDiffAsync(Guid changeId, CancellationToken cancellationToken)
        => Task.FromResult(GitOpsChangeDiff with { ChangeId = changeId });

    public virtual Task<RecentErrorsResponse> GetRecentErrorsAsync(CancellationToken cancellationToken)
        => Task.FromResult(RecentErrors);

    public virtual Task<ObservabilityStatusResponse> GetTelemetryStatusAsync(CancellationToken cancellationToken)
        => Task.FromResult(TelemetryStatus);

    public virtual Task<MigrationObservabilityResponse> GetMigrationStatusAsync(CancellationToken cancellationToken)
        => Task.FromResult(MigrationStatus);

    private static JsonElement Json(string payload)
    {
        using var document = JsonDocument.Parse(payload);
        return document.RootElement.Clone();
    }
}
