// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Honua.Admin.Models.Admin;

namespace Honua.Admin.Services.Admin;

/// <summary>
/// Deterministic in-memory stub for unit tests and the dev shell. Mirrors the
/// <c>StubSpecWorkspaceClient</c> pattern.
/// </summary>
public class StubHonuaAdminClient : IHonuaAdminClient
{
    public static readonly Guid PrimaryConnectionId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");

    public FeatureOverview FeatureOverview { get; init; } = new()
    {
        CurrentEdition = "Enterprise",
        Features =
        [
            new FeatureOverviewItem { Key = "ogc-features", DisplayName = "OGC Features", Category = "Protocol", Description = "OGC API Features support", IsEnabled = true, MinimumEdition = "Community" },
            new FeatureOverviewItem { Key = "tiles", DisplayName = "Tiles", Category = "Protocol", Description = "Vector and raster tile serving", IsEnabled = true, MinimumEdition = "Enterprise" },
            new FeatureOverviewItem { Key = "advanced-observability", DisplayName = "Advanced Observability", Category = "Operations", Description = "Expanded telemetry and alerting", IsEnabled = false, MinimumEdition = "EnterprisePlus", UpgradeMessage = "Requires EnterprisePlus" },
        ],
    };

    public ConfigurationSummary ConfigurationSummary { get; init; } = new()
    {
        TotalTypes = 18,
        RegisteredTypes = 18,
        TotalProperties = 96,
        SecretProperties = 7,
        RequiredProperties = 9,
        TypesWithValidation = 13,
        TotalSecrets = 3,
        ValidSecrets = 3,
        InvalidSecrets = 0,
        Environment = "Development",
        DiscoveryDurationMs = 12,
        LastDiscovery = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public ConfigurationDiscoveryResult ConfigurationDiscovery { get; init; } = new()
    {
        DiscoveredTypes =
        [
            new ConfigurationTypeInfo
            {
                SectionName = "Honua:Database",
                TypeName = "DatabaseOptions",
                FullTypeName = "Honua.Core.Configuration.DatabaseOptions",
                Assembly = "Honua.Core",
                IsRegisteredInDi = true,
                Properties =
                [
                    new PropertyMetadata { Name = "ConnectionString", Type = "String", IsRequired = true, IsSecret = true },
                    new PropertyMetadata { Name = "CommandTimeoutSeconds", Type = "Int32", IsRequired = false, IsSecret = false },
                ],
            },
        ],
        ExtractedMetadata =
        [
            new ConfigurationMetadata { SectionName = "Honua:Database", TypeName = "DatabaseOptions", PropertyCount = 2, SecretPropertyCount = 1, RequiredPropertyCount = 1, HasValidation = true, IsRegistered = true },
        ],
        AutoGeneratedDocumentation =
        [
            new AutoGeneratedDocumentationSection { SectionName = "Honua:Database", TypeName = "DatabaseOptions", Description = "Database connectivity settings" },
        ],
        SecretValidation = new SecretValidationResult { TotalSecrets = 3, ValidSecrets = 3, InvalidSecrets = 0 },
        AuditInformation = new ConfigurationAuditInfo
        {
            Environment = "Development",
            MachineName = "stub-host",
            ApplicationName = "Honua.Server",
            ContentRoot = "/app",
            ConfigurationSources = new Dictionary<string, int> { ["appsettings.json"] = 24 },
            TotalConfigurationKeys = 24,
        },
        DiscoveryDurationMs = 12,
        Timestamp = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public IReadOnlyList<ConnectionSummary> Connections { get; init; } =
    [
        new ConnectionSummary
        {
            ConnectionId = PrimaryConnectionId,
            Name = "primary-postgis",
            Description = "Primary spatial warehouse",
            Host = "db.local",
            Port = 5432,
            DatabaseName = "honua",
            Username = "honua_admin",
            SslRequired = true,
            SslMode = "Require",
            StorageType = "managed",
            IsActive = true,
            HealthStatus = "Healthy",
            CreatedAt = DateTimeOffset.Parse("2026-04-01T00:00:00Z"),
            CreatedBy = "admin",
        },
    ];

    public ConnectionDetail ConnectionDetail { get; init; } = new()
    {
        ConnectionId = PrimaryConnectionId,
        Name = "primary-postgis",
        Description = "Primary spatial warehouse",
        Host = "db.local",
        Port = 5432,
        DatabaseName = "honua",
        Username = "honua_admin",
        SslRequired = true,
        SslMode = "Require",
        StorageType = "managed",
        IsActive = true,
        HealthStatus = "Healthy",
        CreatedAt = DateTimeOffset.Parse("2026-04-01T00:00:00Z"),
        CreatedBy = "admin",
        EncryptionVersion = 3,
        UpdatedAt = DateTimeOffset.Parse("2026-04-20T00:00:00Z"),
    };

    public IReadOnlyList<DiscoveredTable> Tables { get; init; } =
    [
        new DiscoveredTable { Schema = "public", Table = "parcels", GeometryColumn = "geom", GeometryType = "Polygon", Srid = 4326, EstimatedRows = 1250 },
    ];

    public IReadOnlyList<LayerSummary> Layers { get; init; } =
    [
        new LayerSummary { LayerId = 101, LayerName = "Parcels", Schema = "public", Table = "parcels", GeometryType = "Polygon", Srid = 4326, FieldCount = 12, Enabled = true, ServiceName = "default" },
    ];

    public LayerStyle LayerStyle { get; init; } = new()
    {
        MapLibreStyle = Json("""{"version":8,"layers":[]}"""),
        DrawingInfo = Json("""{"renderer":{"type":"simple"}}"""),
    };

    public IReadOnlyList<ServiceSummary> Services { get; init; } =
    [
        new ServiceSummary { ServiceName = "default", Description = "Default feature service", LayerCount = 1, EnabledProtocols = ["FeatureServer", "OgcFeatures"] },
    ];

    public ServiceSettings ServiceSettings { get; init; } = new()
    {
        ServiceName = "default",
        EnabledProtocols = ["FeatureServer", "OgcFeatures"],
        AvailableProtocols = ["FeatureServer", "MapServer", "OgcFeatures", "OData", "Grpc"],
        AccessPolicy = new AccessPolicySettings { AllowAnonymous = true, AllowAnonymousWrite = false, AllowedRoles = ["operator"], AllowedWriteRoles = ["admin"] },
        TimeInfo = new TimeInfoSettings { StartTimeField = "valid_from", EndTimeField = "valid_to" },
        MapServer = new MapServerSettings { MaxImageWidth = 4096, MaxImageHeight = 4096, DefaultImageWidth = 1024, DefaultImageHeight = 768, DefaultDpi = 96, DefaultFormat = "png", DefaultTransparent = true, MaxFeaturesPerLayer = 1000 },
    };

    public DeployPreflightResult DeployPreflight { get; init; } = new()
    {
        Status = "ready",
        ReadyForCoordinatedDeploy = true,
        Message = "Instance is ready for coordinated deployment.",
        ServerVersion = "1.0.0",
        Environment = "Development",
        DeploymentMode = "Standalone",
        InstanceName = "stub-host",
        GeneratedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public DeployPlan DeployPlan { get; init; } = new()
    {
        Target = new DeployPlanTarget { TargetId = "honua-server", TargetName = "Honua Server", TargetKind = "Service", Backend = "stub", Environment = "dev", DesiredRevision = "rev-2", CurrentRevision = "rev-1" },
        ReadyToSubmit = true,
        BackendRegistered = true,
        GeneratedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public DeployOperation DeployOperation { get; init; } = new()
    {
        OperationId = "op-1",
        Kind = "Deploy",
        Status = "AwaitingApproval",
        Priority = "Normal",
        Target = new DeployPlanTarget { TargetId = "honua-server", TargetName = "Honua Server", TargetKind = "Service", Backend = "stub", Environment = "dev", DesiredRevision = "rev-2" },
        CreatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
        UpdatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public RecentErrorsResponse RecentErrors { get; init; } = new()
    {
        Capacity = 50,
        InstanceId = "stub-host-1",
        Errors =
        [
            new RecentErrorEntry { Timestamp = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), CorrelationId = "corr-1", Path = "/api/v1/admin/services", StatusCode = 500, Message = "Sample recent error" },
        ],
    };

    public ObservabilityStatusResponse TelemetryStatus { get; init; } = new()
    {
        TracingEnabled = true,
        OtlpConfigured = true,
        OtlpEndpoint = "http://collector:4317",
    };

    public MigrationObservabilityResponse MigrationStatus { get; init; } = new()
    {
        Status = "succeeded",
        IsReady = true,
        PlanAvailable = true,
        UpgradeRequired = false,
        GeneratedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"),
    };

    public virtual Task<FeatureOverview> GetFeatureOverviewAsync(CancellationToken cancellationToken)
        => Task.FromResult(FeatureOverview);

    public virtual Task<ConfigurationSummary> GetConfigurationSummaryAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationSummary);

    public virtual Task<ConfigurationDiscoveryResult> DiscoverConfigurationAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery);

    public virtual Task<IReadOnlyList<ConfigurationMetadata>> GetConfigurationMetadataAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery.ExtractedMetadata);

    public virtual Task<IReadOnlyList<AutoGeneratedDocumentationSection>> GetConfigurationAutoDocumentationAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery.AutoGeneratedDocumentation);

    public virtual Task<SecretValidationResult> ValidateConfigurationSecretsAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery.SecretValidation);

    public virtual Task<ConfigurationAuditInfo> GetConfigurationAuditInfoAsync(CancellationToken cancellationToken)
        => Task.FromResult(ConfigurationDiscovery.AuditInformation);

    public virtual Task<JsonElement> GetConfigurationDocumentAsync(CancellationToken cancellationToken)
        => Task.FromResult(Json("""{"sections":[{"name":"Honua"}]}"""));

    public virtual Task<JsonElement> GetAdminOpenApiAsync(CancellationToken cancellationToken)
        => Task.FromResult(Json("""{"openapi":"3.0.3","paths":{}}"""));

    public virtual Task<IReadOnlyList<ConnectionSummary>> ListConnectionsAsync(CancellationToken cancellationToken)
        => Task.FromResult(Connections);

    public virtual Task<ConnectionDetail> GetConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => Task.FromResult(ConnectionDetail);

    public virtual Task<ConnectionSummary> CreateConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken)
        => Task.FromResult(Connections[0]);

    public virtual Task<ConnectionSummary> UpdateConnectionAsync(string connectionId, UpdateConnectionRequest request, CancellationToken cancellationToken)
        => Task.FromResult(Connections[0]);

    public virtual Task DeleteConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => Task.CompletedTask;

    public virtual Task<TestConnectionResult> TestDraftConnectionAsync(CreateConnectionRequest request, CancellationToken cancellationToken)
        => Task.FromResult(new TestConnectionResult { ConnectionName = request.Name, IsHealthy = true, TestedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), Message = "Connection is healthy" });

    public virtual Task<TestConnectionResult> TestConnectionAsync(string connectionId, CancellationToken cancellationToken)
        => Task.FromResult(new TestConnectionResult { ConnectionId = PrimaryConnectionId, ConnectionName = "primary-postgis", IsHealthy = true, TestedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), Message = "Connection is healthy" });

    public virtual Task<EncryptionValidationResult> ValidateEncryptionAsync(CancellationToken cancellationToken)
        => Task.FromResult(new EncryptionValidationResult { IsValid = true, CurrentKeyVersion = 3, ValidatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), Message = "Encryption service is working correctly" });

    public virtual Task<KeyRotationResult> RotateEncryptionKeyAsync(CancellationToken cancellationToken)
        => Task.FromResult(new KeyRotationResult { PreviousKeyVersion = 3, NewKeyVersion = 4, RotatedAt = DateTimeOffset.Parse("2026-04-25T00:00:00Z"), Message = "Encryption key rotated successfully" });

    public virtual Task<IReadOnlyList<DiscoveredTable>> DiscoverConnectionTablesAsync(string connectionId, CancellationToken cancellationToken)
        => Task.FromResult(Tables);

    public virtual Task<IReadOnlyList<LayerSummary>> ListLayersAsync(string connectionId, string? serviceName, CancellationToken cancellationToken)
        => Task.FromResult(Layers);

    public virtual Task<LayerSummary> PublishLayerAsync(string connectionId, PublishLayerRequest request, CancellationToken cancellationToken)
        => Task.FromResult(Layers[0]);

    public virtual Task<LayerSummary> SetLayerEnabledAsync(string connectionId, int layerId, bool enabled, string? serviceName, CancellationToken cancellationToken)
        => Task.FromResult(Layers[0] with { Enabled = enabled });

    public virtual Task<IReadOnlyList<LayerSummary>> SetServiceLayersEnabledAsync(string connectionId, bool enabled, string? serviceName, CancellationToken cancellationToken)
        => Task.FromResult<IReadOnlyList<LayerSummary>>([.. Layers.Select(layer => layer with { Enabled = enabled })]);

    public virtual Task<LayerStyle> GetLayerStyleAsync(int layerId, CancellationToken cancellationToken)
        => Task.FromResult(LayerStyle);

    public virtual Task<LayerStyle> UpdateLayerStyleAsync(int layerId, LayerStyleUpdateRequest request, CancellationToken cancellationToken)
        => Task.FromResult(new LayerStyle { MapLibreStyle = request.MapLibreStyle, DrawingInfo = request.DrawingInfo });

    public virtual Task<IReadOnlyList<ServiceSummary>> ListServicesAsync(CancellationToken cancellationToken)
        => Task.FromResult(Services);

    public virtual Task<ServiceSettings> GetServiceSettingsAsync(string serviceName, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings);

    public virtual Task<ServiceSettings> UpdateServiceProtocolsAsync(string serviceName, UpdateProtocolsRequest request, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings with { EnabledProtocols = request.EnabledProtocols });

    public virtual Task<ServiceSettings> UpdateServiceMapServerAsync(string serviceName, MapServerSettings request, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings with { MapServer = request });

    public virtual Task<ServiceSettings> UpdateServiceAccessPolicyAsync(string serviceName, AccessPolicySettings request, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings with { AccessPolicy = request });

    public virtual Task<ServiceSettings> UpdateServiceTimeInfoAsync(string serviceName, TimeInfoSettings request, CancellationToken cancellationToken)
        => Task.FromResult(ServiceSettings with { TimeInfo = request });

    public virtual Task<LayerMetadataResponse> UpdateServiceLayerMetadataAsync(string serviceName, int layerId, UpdateLayerMetadataRequest request, CancellationToken cancellationToken)
        => Task.FromResult(new LayerMetadataResponse { LayerId = layerId, LayerName = "Parcels", AccessPolicy = request.AccessPolicy, TimeInfo = request.TimeInfo });

    public virtual Task<DeployPreflightResult> GetDeployPreflightAsync(CancellationToken cancellationToken)
        => Task.FromResult(DeployPreflight);

    public virtual Task<DeployPlan> PlanDeployAsync(DeployPlanRequest request, CancellationToken cancellationToken)
        => Task.FromResult(DeployPlan with { Target = DeployPlan.Target with { TargetId = request.TargetId, DesiredRevision = request.DesiredRevision, CurrentRevision = request.CurrentRevision } });

    public virtual Task<DeployOperation> CreateDeployOperationAsync(CreateDeployOperationRequest request, CancellationToken cancellationToken)
        => Task.FromResult(DeployOperation);

    public virtual Task<DeployOperation> GetDeployOperationAsync(string operationId, CancellationToken cancellationToken)
        => Task.FromResult(DeployOperation with { OperationId = operationId });

    public virtual Task<DeployOperation> SubmitDeployOperationAsync(string operationId, SubmitDeployOperationRequest request, CancellationToken cancellationToken)
        => Task.FromResult(DeployOperation with { OperationId = operationId, Status = "Submitted", Reason = request.Reason });

    public virtual Task<DeployOperation> RollbackDeployOperationAsync(string operationId, RollbackDeployOperationRequest request, CancellationToken cancellationToken)
        => Task.FromResult(DeployOperation with { OperationId = operationId, Status = "RollbackRequested", Reason = request.Reason });

    public virtual Task<RecentErrorsResponse> GetRecentErrorsAsync(CancellationToken cancellationToken)
        => Task.FromResult(RecentErrors);

    public virtual Task<ObservabilityStatusResponse> GetTelemetryStatusAsync(CancellationToken cancellationToken)
        => Task.FromResult(TelemetryStatus);

    public virtual Task<MigrationObservabilityResponse> GetMigrationStatusAsync(CancellationToken cancellationToken)
        => Task.FromResult(MigrationStatus);

    private static JsonElement Json(string payload)
    {
        using var document = JsonDocument.Parse(payload);
        return document.RootElement.Clone();
    }
}
